import tkinter as tk
from tkinter import ttk

piece_772 = {
    "aqua": 6,
    "black": 289,
    "blue": 46,
    "blue_violet": 4,
    "bright_green": 6,
    "bright_light_blue": 4,
    "bright_light_orange": 3,
    "bright_light_yellow": 8,
    "bright_pink": 2,
    "brown": 57,
    "dark_azure": 4,
    "dark_blue": 19,
    "dark_blue_violet": 6,
    "dark_bluish_gray": 1033,
    "dark_brown": 17,
    "dark_gray": 64,
    "dark_green": 24,
    "dark_nougat": 7,
    "dark_orange": 8,
    "dark_pink": 2,
    "dark_purple": 2,
    "dark_red": 56,
    "dark_tan": 18,
    "dark_turquoise": 3,
    "earth_orange": 4,
    "fabuland_brown": 8,
    "fabuland_orange": 1,
    "green": 8,
    "light_blue": 1,
    "light_bluish_gray": 830,
    "light_brown": 19,
    "light_gray": 142,
    "light_green": 2,
    "light_nougat": 3,
    "light_pink": 2,
    "light_salmon": 2,
    "light_turquoise": 1,
    "light_violet": 2,
    "light_yellow": 15,
    "lime": 1,
    "maersk_blue": 3,
    "magenta": 2,
    "medium_azure": 1,
    "medium_blue": 19,
    "medium_brown": 3,
    "medium_dark_pink": 1,
    "medium_lavender": 1,
    "medium_lime": 1,
    "medium_nougat": 13,
    "medium_orange": 1,
    "medium_tan": 6,
    "neon_green": 1,
    "nougat": 16,
    "olive_green": 7,
    "orange": 5,
    "pink": 3,
    "purple": 2,
    "red": 307,
    "reddish_brown": 33,
    "rust": 11,
    "salmon": 1,
    "sand_blue": 7,
    "sand_green": 4,
    "sand_purple": 3,
    "sky_blue": 1,
    "tan": 1028,
    "very_light_bluish_gray": 10,
    "very_light_gray": 22,
    "very_light_orange": 1,
    "white": 1803,
    "yellow": 27,
    "yellowish_green": 3,
    "trans_brown": 18,
    "trans_clear": 180,
    "trans_dark_blue": 3,
    "trans_light_blue": 11,
    "trans_medium_blue": 5,
    "trans_neon_green": 1,
    "trans_neon_orange": 1,
    "trans_orange": 3,
    "trans_pink": 1,
    "chrome_silver": 2,
    "copper": 1,
    "flat_silver": 45,
    "pearl_dark_gray": 3,
    "pearl_gold": 5,
    "pearl_light_gold": 1,
    "pearl_sand_blue": 2,
    "metallic_green": 1,
    "metallic_silver": 4
}

piece_2038 = {
    "black": 10,
    "blue": 10,
    "brown": 10,
    "dark_green": 10,
    "dark_pink": 10,
    "green": 10,
    "light_gray": 10,
    "red": 10,
    "reddish_brown": 10,
    "tan": 10,
    "white": 10,
    "yellow": 10,
    "chrome_silver": 10,
    "flat_silver": 10
}

piece_2039 = {
    "black": 10,
    "blue": 10,
    "bright_light_blue": 10,
    "brown": 10,
    "dark_blue": 10,
    "dark_bluish_gray": 10,
    "dark_brown": 10,
    "dark_gray": 10,
    "dark_green": 10,
    "dark_purple": 10,
    "dark_tan": 10,
    "dark_turquoise": 10,
    "green": 10,
    "light_bluish_gray": 10,
    "light_gray": 10,
    "light_turquoise": 10,
    "medium_lavender": 10,
    "pink": 10,
    "red": 10,
    "sand_blue": 10,
    "sand_green": 10,
    "tan": 10,
    "violet": 10,
    "white": 10,
    "yellow": 10,
    "trans_red": 10,
    "flat_silver": 10,
    "pearl_black": 10,
    "pearl_dark_gray": 10,
    "reddish_gold": 10,
    "satin_trans_clear": 10
}

piece_2335 = {
    "aqua": 10,
    "black": 10,
    "blue": 10,
    "bright_green": 10,
    "bright_light_blue": 10,
    "bright_light_orange": 10,
    "bright_light_yellow": 10,
    "bright_pink": 10,
    "brown": 10,
    "dark_azure": 10,
    "dark_blue": 10,
    "dark_blue_violet": 10,
    "dark_bluish_gray": 10,
    "dark_brown": 10,
    "dark_gray": 10,
    "dark_green": 10,
    "dark_orange": 10,
    "dark_pink": 10,
    "dark_purple": 10,
    "dark_red": 10,
    "dark_tan": 10,
    "dark_turquoise": 10,
    "dark_yellow": 10,
    "earth_orange": 10,
    "green": 10,
    "light_aqua": 10,
    "light_bluish_gray": 10,
    "light_brown": 10,
    "light_gray": 10,
    "light_nougat": 10,
    "light_pink": 10,
    "light_purple": 10,
    "light_turquoise": 10,
    "light_yellow": 10,
    "lime": 10,
    "maersk_blue": 10,
    "magenta": 10,
    "medium_azure": 10,
    "medium_blue": 10,
    "medium_lavender": 10,
    "medium_nougat": 10,
    "medium_orange": 10,
    "medium_violet": 10,
    "neon_orange": 10,
    "nougat": 10,
    "olive_green": 10,
    "orange": 10,
    "pink": 10,
    "purple": 10,
    "red": 10,
    "reddish_brown": 10,
    "rust": 10,
    "sand_blue": 10,
    "sand_green": 10,
    "sky_blue": 10,
    "tan": 10,
    "very_light_bluish_gray": 10,
    "very_light_gray": 10,
    "white": 10,
    "yellow": 10,
    "yellowish_green": 10,
    "trans_aqua": 10,
    "trans_brown": 10,
    "trans_clear": 10,
    "trans_dark_blue": 10,
    "trans_light_blue": 10,
    "trans_neon_green": 10,
    "trans_purple": 10,
    "trans_red": 10,
    "chrome_black": 10,
    "chrome_blue": 10,
    "chrome_silver": 10,
    "flat_silver": 10,
    "pearl_dark_gray": 10,
    "pearl_gold": 10,
    "pearl_light_gray": 10,
    "metallic_silver": 10
}

piece_2336 = {
    "black": 16,
    "blue": 8,
    "dark_bluish_gray": 1,
    "dark_gray": 1,
    "green": 2,
    "light_gray": 4,
    "orange": 214,
    "red": 10,
    "tan": 3,
    "white": 14,
    "yellow": 2
}

piece_2338 = {
    "black": 556,
    "blue": 1,
    "brown": 1,
    "green": 1,
    "orange": 3,
    "red": 1025,
    "tan": 2,
    "white": 533,
    "yellow": 2,
    "trans_clear": 2
}

piece_2339 = {
    "black": 28729,
    "blue": 109,
    "bright_green": 1,
    "bright_light_blue": 1,
    "bright_light_orange": 1,
    "bright_light_yellow": 2,
    "brown": 2906,
    "dark_azure": 1,
    "dark_blue": 6315,
    "dark_blue_violet": 1,
    "dark_bluish_gray": 17715,
    "dark_brown": 6488,
    "dark_gray": 278,
    "dark_green": 13,
    "dark_nougat": 2,
    "dark_orange": 9,
    "dark_pink": 1,
    "dark_purple": 62,
    "dark_red": 35,
    "dark_tan": 829,
    "dark_turquoise": 141,
    "earth_orange": 1,
    "fabuland_brown": 15,
    "green": 301,
    "lavender": 128,
    "light_bluish_gray": 32947,
    "light_brown": 9,
    "light_gray": 4904,
    "light_nougat": 2,
    "light_orange": 1,
    "light_pink": 2,
    "light_yellow": 42,
    "medium_blue": 5,
    "medium_brown": 3,
    "medium_lavender": 201,
    "medium_nougat": 750,
    "medium_tan": 1,
    "nougat": 1,
    "olive_green": 3,
    "orange": 4,
    "purple": 1,
    "red": 3342,
    "reddish_brown": 31104,
    "salmon": 1,
    "sand_green": 11,
    "tan": 11701,
    "very_light_bluish_gray": 13,
    "very_light_gray": 5,
    "very_light_orange": 1,
    "white": 10031,
    "yellow": 2214,
    "trans_dark_blue": 2,
    "trans_green": 1,
    "trans_light_orange": 2,
    "chrome_gold": 1,
    "pearl_dark_gray": 7,
    "pearl_gold": 4
}

piece_2340 = {
    "black": 6311,
    "blue": 2849,
    "bright_green": 1,
    "bright_light_blue": 1,
    "bright_light_orange": 121,
    "bright_pink": 1,
    "clikits_lavender": 2,
    "dark_azure": 1,
    "dark_blue": 326,
    "dark_bluish_gray": 1478,
    "dark_gray": 287,
    "dark_green": 5,
    "dark_orange": 204,
    "dark_pink": 1,
    "dark_purple": 2,
    "dark_red": 129,
    "dark_tan": 2,
    "dark_turquoise": 382,
    "green": 11,
    "light_aqua": 1,
    "light_bluish_gray": 1657,
    "light_gray": 1129,
    "magenta": 131,
    "medium_azure": 381,
    "medium_lime": 1,
    "medium_nougat": 1,
    "olive_green": 1,
    "orange": 313,
    "red": 2694,
    "reddish_brown": 78,
    "sand_blue": 1,
    "sand_green": 1,
    "sky_blue": 1,
    "tan": 6,
    "very_light_bluish_gray": 10,
    "white": 5980,
    "yellow": 580,
    "trans_clear": 29,
    "trans_green": 1,
    "trans_neon_yellow": 1,
    "trans_orange": 1,
    "pearl_dark_gray": 1,
    "milky_white": 1
}

piece_2341 = {
    "black": 4719,
    "blue": 30,
    "bright_green": 1,
    "bright_light_orange": 3,
    "brown": 46,
    "dark_azure": 2,
    "dark_blue": 25,
    "dark_blue_violet": 1,
    "dark_bluish_gray": 11866,
    "dark_brown": 23,
    "dark_gray": 58,
    "dark_green": 7,
    "dark_orange": 2,
    "dark_pink": 2,
    "dark_purple": 128,
    "dark_red": 1072,
    "dark_tan": 11,
    "earth_orange": 16,
    "fabuland_brown": 16,
    "fabuland_orange": 1,
    "green": 9,
    "light_aqua": 23,
    "light_blue": 1,
    "light_bluish_gray": 24589,
    "light_brown": 4,
    "light_gray": 1835,
    "light_green": 16,
    "light_nougat": 6,
    "lime": 3,
    "magenta": 1,
    "medium_azure": 312,
    "medium_blue": 4,
    "medium_nougat": 2,
    "medium_orange": 1,
    "olive_green": 2,
    "orange": 27,
    "purple": 1,
    "red": 2086,
    "reddish_brown": 75,
    "rust": 2,
    "sand_blue": 2,
    "sand_green": 11,
    "tan": 2740,
    "very_light_bluish_gray": 15,
    "very_light_gray": 5,
    "white": 4822,
    "yellow": 207,
    "trans_bright_green": 2,
    "chrome_black": 2,
    "chrome_gold": 2,
    "chrome_silver": 6,
    "copper": 4,
    "flat_silver": 3,
    "pearl_dark_gray": 3,
    "pearl_gold": 2,
    "metallic_silver": 3,
    "glow_in_dark_white": 4,
}

piece_2342 = {
    "black": 3751,
    "blue": 745,
    "bright_light_yellow": 2,
    "brown": 15,
    "dark_bluish_gray": 96,
    "dark_brown": 21,
    "dark_gray": 846,
    "dark_green": 1,
    "dark_red": 7,
    "dark_tan": 20,
    "dark_turquoise": 339,
    "green": 31,
    "light_bluish_gray": 78,
    "light_gray": 1663,
    "light_nougat": 1,
    "orange": 1,
    "red": 405,
    "reddish_brown": 6,
    "sand_blue": 1,
    "tan": 29,
    "very_light_bluish_gray": 3,
    "white": 2703,
    "yellow": 764,
    "flat_silver": 2,
    "pearl_black": 1,
    "pearl_dark_gray": 7
}

piece_2453a = {
    "aqua": 5,
    "black": 9623,
    "blue": 717,
    "blue_violet": 3,
    "bright_green": 10,
    "bright_light_blue": 5,
    "bright_light_orange": 10,
    "bright_light_yellow": 35,
    "brown": 808,
    "clikits_lavender": 2,
    "dark_azure": 1,
    "dark_blue": 22,
    "dark_blue_violet": 2,
    "dark_bluish_gray": 7129,
    "dark_brown": 66,
    "dark_gray": 518,
    "dark_green": 535,
    "dark_nougat": 5,
    "dark_orange": 420,
    "dark_pink": 107,
    "dark_purple": 21,
    "dark_red": 2152,
    "dark_tan": 81,
    "dark_turquoise": 19,
    "dark_yellow": 3,
    "earth_orange": 1,
    "fabuland_brown": 18,
    "fabuland_orange": 2,
    "green": 38,
    "lavender": 6,
    "light_aqua": 2,
    "light_blue": 1,
    "light_bluish_gray": 8860,
    "light_brown": 46,
    "light_gray": 4574,
    "light_lime": 1,
    "light_nougat": 7,
    "light_orange": 3,
    "light_pink": 1,
    "light_purple": 2,
    "light_salmon": 1,
    "light_turquoise": 2,
    "light_yellow": 165,
    "lime": 5,
    "maersk_blue": 6,
    "magenta": 18,
    "medium_azure": 8,
    "medium_blue": 12,
    "medium_brown": 4,
    "medium_green": 3,
    "medium_lavender": 2,
    "medium_lime": 1,
    "medium_nougat": 125,
    "medium_orange": 4,
    "medium_tan": 6,
    "neon_green": 1,
    "nougat": 14,
    "olive_green": 4,
    "orange": 313,
    "pink": 1,
    "purple": 1,
    "red": 3068,
    "reddish_brown": 4844,
    "rust": 11,
    "sand_blue": 17,
    "sand_green": 70,
    "sky_blue": 6,
    "tan": 5556,
    "very_light_bluish_gray": 29,
    "very_light_gray": 28,
    "very_light_orange": 7,
    "violet": 4,
    "white": 12584,
    "yellow": 2109,
    "trans_brown": 10,
    "trans_clear": 109,
    "trans_dark_blue": 3,
    "trans_dark_pink": 2,
    "trans_light_blue": 16,
    "trans_medium_blue": 16,
    "trans_neon_orange": 1,
    "trans_orange": 1,
    "trans_yellow": 1,
    "chrome_black": 2,
    "chrome_gold": 3,
    "chrome_silver": 3,
    "copper": 4,
    "flat_dark_gold": 1,
    "flat_silver": 30,
    "pearl_black": 2,
    "pearl_dark_gray": 7,
    "pearl_gold": 10,
    "pearl_light_gold": 1,
    "pearl_light_gray": 3,
    "pearl_white": 1,
    "metallic_gold": 1,
    "metallic_silver": 10,
    "glow_in_dark_white": 4,
}

piece_2453b = {
    "aqua": 4,
    "black": 16164,
    "blue": 566,
    "blue_violet": 5,
    "bright_green": 12,
    "bright_light_blue": 12,
    "bright_light_orange": 1005,
    "bright_light_yellow": 1559,
    "bright_pink": 564,
    "brown": 256,
    "clikits_lavender": 2,
    "dark_azure": 7,
    "dark_blue": 33,
    "dark_blue_violet": 7,
    "dark_bluish_gray": 18064,
    "dark_brown": 295,
    "dark_gray": 129,
    "dark_green": 59,
    "dark_nougat": 6,
    "dark_orange": 63,
    "dark_pink": 4,
    "dark_purple": 319,
    "dark_red": 2592,
    "dark_salmon": 1,
    "dark_tan": 124,
    "dark_turquoise": 305,
    "dark_yellow": 1,
    "earth_orange": 4,
    "fabuland_brown": 63,
    "fabuland_lime": 2,
    "fabuland_orange": 4,
    "green": 85,
    "lavender": 107,
    "light_aqua": 600,
    "light_blue": 5,
    "light_bluish_gray": 32322,
    "light_brown": 40,
    "light_gray": 340,
    "light_green": 1,
    "light_lime": 1,
    "light_nougat": 48,
    "light_orange": 4,
    "light_pink": 1,
    "light_purple": 2,
    "light_turquoise": 4,
    "light_yellow": 21,
    "lime": 48,
    "maersk_blue": 1,
    "magenta": 127,
    "medium_azure": 305,
    "medium_blue": 14,
    "medium_brown": 6,
    "medium_green": 4,
    "medium_lavender": 1,
    "medium_lime": 2,
    "medium_nougat": 3376,
    "medium_orange": 2,
    "medium_tan": 12,
    "neon_green": 1,
    "neon_orange": 4,
    "neon_yellow": 2,
    "nougat": 24,
    "olive_green": 3,
    "orange": 133,
    "pink": 2,
    "purple": 8,
    "red": 5098,
    "reddish_brown": 27722,
    "rust": 21,
    "salmon": 1,
    "sand_blue": 68,
    "sand_green": 1898,
    "sand_red": 1,
    "sky_blue": 7,
    "tan": 26492,
    "very_light_bluish_gray": 14,
    "very_light_gray": 37,
    "very_light_orange": 4,
    "violet": 1,
    "white": 37376,
    "yellow": 3075,
    "yellowish_green": 76,
    "trans_aqua": 1,
    "trans_black": 2,
    "trans_bright_green": 1,
    "trans_brown": 19,
    "trans_clear": 86,
    "trans_dark_blue": 4,
    "trans_light_blue": 19,
    "trans_light_purple": 1,
    "trans_medium_blue": 35,
    "trans_neon_orange": 2,
    "trans_neon_yellow": 3,
    "trans_orange": 1,
    "trans_red": 1,
    "trans_yellow": 16,
    "chrome_antique_brass": 1,
    "chrome_black": 1,
    "chrome_gold": 4,
    "chrome_silver": 4,
    "copper": 3,
    "flat_silver": 48,
    "pearl_black": 7,
    "pearl_dark_gray": 6,
    "pearl_gold": 82,
    "pearl_light_gray": 3,
    "pearl_white": 2,
    "satin_trans_clear": 1,
    "metallic_copper": 2,
    "metallic_gold": 4,
    "metallic_green": 1,
    "metallic_silver": 4,
    "glow_in_dark_white": 7,
}

piece_2454 = {
    "aqua": 10,
    "black": 36398,
    "blue": 4131,
    "blue_violet": 218,
    "bright_green": 13,
    "bright_light_blue": 45,
    "bright_light_orange": 114,
    "bright_light_yellow": 1288,
    "bright_pink": 171,
    "brown": 675,
    "clikits_lavender": 2,
    "coral": 1,
    "dark_azure": 8,
    "dark_blue": 784,
    "dark_blue_violet": 7,
    "dark_bluish_gray": 35019,
    "dark_brown": 43,
    "dark_gray": 2924,
    "dark_green": 379,
    "dark_nougat": 4,
    "dark_orange": 978,
    "dark_pink": 13,
    "dark_purple": 525,
    "dark_red": 2206,
    "dark_salmon": 1,
    "dark_tan": 256,
    "dark_turquoise": 8,
    "dark_yellow": 3,
    "earth_orange": 8,
    "fabuland_brown": 17,
    "fabuland_orange": 1,
    "green": 841,
    "lavender": 1402,
    "light_aqua": 879,
    "light_blue": 5,
    "light_bluish_gray": 41640,
    "light_brown": 18,
    "light_gray": 5412,
    "light_green": 4,
    "light_lime": 2,
    "light_nougat": 109,
    "light_orange": 2,
    "light_pink": 2,
    "light_purple": 1,
    "light_salmon": 2,
    "light_turquoise": 4,
    "light_yellow": 275,
    "lime": 44,
    "maersk_blue": 4,
    "magenta": 1125,
    "medium_azure": 178,
    "medium_blue": 19,
    "medium_brown": 1,
    "medium_green": 3,
    "medium_lavender": 367,
    "medium_lime": 2,
    "medium_nougat": 3610,
    "medium_orange": 840,
    "medium_tan": 7,
    "medium_violet": 56,
    "neon_orange": 3,
    "nougat": 40,
    "olive_green": 358,
    "orange": 388,
    "pink": 3,
    "purple": 4,
    "red": 11548,
    "reddish_brown": 13347,
    "rust": 4,
    "salmon": 1,
    "sand_blue": 71,
    "sand_green": 2058,
    "sand_purple": 12,
    "sand_red": 2,
    "sky_blue": 15,
    "tan": 47243,
    "very_light_bluish_gray": 69,
    "very_light_gray": 18,
    "very_light_orange": 7,
    "violet": 3,
    "white": 52843,
    "yellow": 3367,
    "yellowish_green": 1,
    "trans_aqua": 1,
    "trans_black": 101,
    "trans_clear": 871,
    "trans_dark_blue": 62,
    "trans_dark_pink": 9,
    "trans_light_blue": 334,
    "trans_light_orange": 4,
    "trans_medium_blue": 41,
    "trans_neon_green": 18,
    "trans_neon_orange": 3,
    "trans_orange": 27,
    "trans_purple": 3,
    "trans_red": 8,
    "trans_yellow": 3,
    "chrome_black": 3,
    "chrome_gold": 5,
    "chrome_silver": 3,
    "copper": 2,
    "flat_silver": 39,
    "pearl_dark_gray": 19,
    "pearl_gold": 8,
    "pearl_light_gray": 1,
    "satin_trans_clear": 1,
    "satin_trans_light_blue": 1,
    "metallic_gold": 1,
    "metallic_silver": 10,
    "glow_in_dark_white": 12,
    "milky_white": 1,
}

piece_22886 = {
    "aqua": 3,
    "black": 2824,
    "blue": 87,
    "blue_violet": 2,
    "bright_green": 17,
    "bright_light_blue": 8,
    "bright_light_orange": 139,
    "bright_light_yellow": 17,
    "bright_pink": 68,
    "brown": 93,
    "clikits_lavender": 1,
    "coral": 3,
    "dark_azure": 12,
    "dark_blue": 129,
    "dark_blue_violet": 6,
    "dark_bluish_gray": 1740,
    "dark_brown": 94,
    "dark_gray": 105,
    "dark_green": 82,
    "dark_nougat": 1,
    "dark_orange": 1219,
    "dark_pink": 2,
    "dark_purple": 11,
    "dark_red": 81,
    "dark_tan": 2502,
    "dark_turquoise": 17,
    "dark_yellow": 1,
    "earth_orange": 8,
    "fabuland_brown": 14,
    "fabuland_orange": 3,
    "green": 163,
    "light_aqua": 267,
    "light_blue": 4,
    "light_bluish_gray": 19145,
    "light_brown": 33,
    "light_gray": 335,
    "light_nougat": 20,
    "light_orange": 3,
    "light_pink": 2,
    "light_purple": 1,
    "light_salmon": 10,
    "light_turquoise": 4,
    "light_violet": 5,
    "light_yellow": 58,
    "lime": 4,
    "maersk_blue": 1,
    "magenta": 4,
    "medium_azure": 7,
    "medium_blue": 299,
    "medium_brown": 9,
    "medium_dark_pink": 2,
    "medium_green": 3,
    "medium_lavender": 5,
    "medium_lime": 1,
    "medium_nougat": 31,
    "medium_orange": 17,
    "medium_tan": 3,
    "medium_violet": 1,
    "nougat": 17,
    "olive_green": 44,
    "orange": 29,
    "pink": 4,
    "purple": 3,
    "red": 221,
    "reddish_brown": 626,
    "rust": 14,
    "salmon": 3,
    "sand_blue": 76,
    "sand_green": 920,
    "sky_blue": 8,
    "tan": 770,
    "very_light_bluish_gray": 91,
    "very_light_gray": 17,
    "very_light_orange": 7,
    "white": 15839,
    "yellow": 1162,
    "trans_aqua": 24,
    "trans_black": 2,
    "trans_brown": 21,
    "trans_clear": 84,
    "trans_dark_blue": 2,
    "trans_light_blue": 16,
    "trans_light_green": 1,
    "trans_light_orange": 1,
    "trans_medium_blue": 25,
    "trans_neon_green": 1,
    "trans_neon_orange": 1,
    "trans_neon_yellow": 1,
    "trans_orange": 3,
    "trans_red": 3,
    "trans_yellow": 1,
    "chrome_black": 7,
    "chrome_gold": 12,
    "chrome_silver": 1,
    "copper": 1,
    "flat_dark_gold": 2,
    "flat_silver": 88,
    "pearl_black": 1,
    "pearl_dark_gray": 19,
    "pearl_gold": 4,
    "pearl_light_gray": 8,
    "pearl_very_light_gray": 1,
    "metallic_gold": 2,
    "metallic_green": 2,
    "metallic_silver": 9,
    "glow_in_dark_white": 9
}

piece_3001 = {
    "aqua": 10,
    "black": 10,
    "blue": 10,
    "blue_violet": 10,
    "bright_green": 10,
    "bright_light_blue": 10,
    "bright_light_orange": 10,
    "bright_light_yellow": 10,
    "bright_pink": 10,
    "brown": 10,
    "clikits_lavender": 10,
    "coral": 10,
    "dark_azure": 10,
    "dark_blue": 10,
    "dark_blue_violet": 10,
    "dark_bluish_gray": 10,
    "dark_brown": 10,
    "dark_gray": 10,
    "dark_green": 10,
    "dark_nougat": 10,
    "dark_olive_green": 10,
    "dark_orange": 10,
    "dark_pink": 10,
    "dark_purple": 10,
    "dark_red": 10,
    "dark_salmon": 10,
    "dark_tan": 10,
    "dark_turquoise": 10,
    "dark_yellow": 10,
    "earth_orange": 10,
    "fabuland_brown": 10,
    "fabuland_lime": 10,
    "fabuland_orange": 10,
    "green": 10,
    "lavender": 10,
    "light_aqua": 10,
    "light_blue": 10,
    "light_bluish_gray": 10,
    "light_brown": 10,
    "light_gray": 10,
    "light_green": 10,
    "light_lilac": 10,
    "light_lime": 10,
    "light_nougat": 10,
    "light_orange": 10,
    "light_pink": 10,
    "light_purple": 10,
    "light_salmon": 10,
    "light_turquoise": 10,
    "light_violet": 10,
    "light_yellow": 10,
    "lilac": 10,
    "lime": 10,
    "little_robots_blue": 10,
    "maersk_blue": 10,
    "magenta": 10,
    "medium_azure": 10,
    "medium_blue": 10,
    "medium_brown": 10,
    "medium_dark_pink": 10,
    "medium_green": 10,
    "medium_lavender": 10,
    "medium_lime": 10,
    "medium_nougat": 10,
    "medium_orange": 10,
    "medium_tan": 10,
    "medium_violet": 10,
    "neon_green": 10,
    "neon_orange": 10,
    "neon_yellow": 10,
    "nougat": 10,
    "olive_green": 10,
    "orange": 10,
    "pink": 10,
    "purple": 10,
    "red": 10,
    "reddish_brown": 10,
    "rust": 10,
    "salmon": 10,
    "sand_blue": 10,
    "sand_green": 10,
    "sand_purple": 10,
    "sand_red": 10,
    "sky_blue": 10,
    "tan": 10,
    "very_light_bluish_gray": 10,
    "very_light_gray": 10,
    "very_light_orange": 10,
    "violet": 10,
    "white": 10,
    "yellow": 10,
    "yellowish_green": 10,
    "trans_aqua": 10,
    "trans_black": 10,
    "trans_bright_green": 10,
    "trans_brown": 10,
    "trans_clear": 10,
    "trans_dark_blue": 10,
    "trans_dark_pink": 10,
    "trans_green": 10,
    "trans_light_blue": 10,
    "trans_light_bright_green": 10,
    "trans_light_green": 10,
    "trans_light_orange": 10,
    "trans_light_purple": 10,
    "trans_medium_blue": 10,
    "trans_medium_purple": 10,
    "trans_neon_green": 10,
    "trans_neon_orange": 10,
    "trans_neon_yellow": 10,
    "trans_orange": 10,
    "trans_pink": 10,
    "trans_purple": 10,
    "trans_red": 10,
    "trans_yellow": 10,
    "chrome_antique_brass": 10,
    "chrome_black": 10,
    "chrome_blue": 10,
    "chrome_gold": 10,
    "chrome_green": 10,
    "chrome_pink": 10,
    "chrome_silver": 10,
    "bionicle_copper": 10,
    "bionicle_gold": 10,
    "bionicle_silver": 10,
    "copper": 10,
    "flat_dark_gold": 10,
    "flat_silver": 10,
    "pearl_black": 10,
    "pearl_blue": 10,
    "pearl_brown": 10,
    "pearl_dark_gray": 10,
    "pearl_gold": 10,
    "pearl_green": 10,
    "pearl_light_gold": 10,
    "pearl_light_gray": 10,
    "pearl_red": 10,
    "pearl_sand_blue": 10,
    "pearl_sand_purple": 10,
    "pearl_very_light_gray": 10,
    "pearl_white": 10,
    "reddish_copper": 10,
    "reddish_gold": 10,
    "satin_trans_bright_green": 10,
    "satin_trans_brown": 10,
    "satin_trans_clear": 10,
    "satin_trans_dark_blue": 10,
    "satin_trans_dark_pink": 10,
    "satin_trans_light_blue": 10,
    "satin_trans_purple": 10,
    "metallic_copper": 10,
    "metallic_gold": 10,
    "metallic_green": 10,
    "metallic_silver": 10,
    "glow_in_dark_opaque": 10,
    "glow_in_dark_trans": 10,
    "glow_in_dark_white": 10,
    "milky_white": 10,
    "glitter_trans_clear": 10,
    "glitter_trans_dark_pink": 10,
    "glitter_trans_light_blue": 10,
    "glitter_trans_neon_green": 10,
    "glitter_trans_orange": 10,
    "glitter_trans_purple": 10,
}

piece_3004 = {
    "Aqua": 10,
    "Black": 10,
    "Blue": 10,
    "Blue-Violet": 10,
    "Bright Green": 10,
    "Bright Light Blue": 10,
    "Bright Light Orange": 10,
    "Bright Light Yellow": 10,
    "Bright Pink": 10,
    "Brown": 10,
    "Clikits Lavender": 10,
    "Coral": 10,
    "Dark Azure": 10,
    "Dark Blue": 10,
    "Dark Blue-Violet": 10,
    "Dark Bluish Gray": 10,
    "Dark Brown": 10,
    "Dark Gray": 10,
    "Dark Green": 10,
    "Dark Nougat": 10,
    "Dark Olive Green": 10,
    "Dark Orange": 10,
    "Dark Pink": 10,
    "Dark Purple": 10,
    "Dark Red": 10,
    "Dark Salmon": 10,
    "Dark Tan": 10,
    "Dark Turquoise": 10,
    "Dark Yellow": 10,
    "Earth Orange": 10,
    "Fabuland Brown": 10,
    "Fabuland Lime": 10,
    "Fabuland Orange": 10,
    "Green": 10,
    "Lavender": 10,
    "Light Aqua": 10,
    "Light Blue": 10,
    "Light Bluish Gray": 10,
    "Light Brown": 10,
    "Light Gray": 10,
    "Light Green": 10,
    "Light Lilac": 10,
    "Light Lime": 10,
    "Light Nougat": 10,
    "Light Orange": 10,
    "Light Pink": 10,
    "Light Purple": 10,
    "Light Salmon": 10,
    "Light Turquoise": 10,
    "Light Violet": 10,
    "Light Yellow": 10,
    "Lilac": 10,
    "Lime": 10,
    "Little Robots Blue": 10,
    "Maersk Blue": 10,
    "Magenta": 10,
    "Medium Azure": 10,
    "Medium Blue": 10,
    "Medium Brown": 10,
    "Medium Dark Pink": 10,
    "Medium Green": 10,
    "Medium Lavender": 10,
    "Medium Lime": 10,
    "Medium Nougat": 10,
    "Medium Orange": 10,
    "Medium Tan": 10,
    "Medium Violet": 10,
    "Neon Green": 10,
    "Neon Orange": 10,
    "Neon Yellow": 10,
    "Nougat": 10,
    "Olive Green": 10,
    "Orange": 10,
    "Pink": 10,
    "Purple": 10,
    "Red": 10,
    "Reddish Brown": 10,
    "Rust": 10,
    "Salmon": 10,
    "Sand Blue": 10,
    "Sand Green": 10,
    "Sand Purple": 10,
    "Sand Red": 10,
    "Sky Blue": 10,
    "Tan": 10,
    "Very Light Bluish Gray": 10,
    "Very Light Gray": 10,
    "Very Light Orange": 10,
    "Violet": 10,
    "White": 10,
    "Yellow": 10,
    "Yellowish Green": 10,
    "Trans-Aqua": 10,
    "Trans-Black": 10,
    "Trans-Bright Green": 10,
    "Trans-Brown (Old Trans-Black)": 10,
    "Trans-Clear": 10,
    "Trans-Dark Blue": 10,
    "Trans-Dark Pink": 10,
    "Trans-Green": 10,
    "Trans-Light Blue": 10,
    "Trans-Light Bright Green": 10,
    "Trans-Light Green": 10,
    "Trans-Light Orange": 10,
    "Trans-Light Purple": 10,
    "Trans-Medium Blue": 10,
    "Trans-Medium Purple": 10,
    "Trans-Neon Green": 10,
    "Trans-Neon Orange": 10,
    "Trans-Neon Yellow": 10,
    "Trans-Orange": 10,
    "Trans-Pink": 10,
    "Trans-Purple": 10,
    "Trans-Red": 10,
    "Trans-Yellow": 10,
    "Chrome Antique Brass": 10,
    "Chrome Black": 10,
    "Chrome Blue": 10,
    "Chrome Gold": 10,
    "Chrome Green": 10,
    "Chrome Pink": 10,
    "Chrome Silver": 10,
    "Bionicle Copper": 10,
    "Bionicle Gold": 10,
    "Bionicle Silver": 10,
    "Copper": 10,
    "Flat Dark Gold": 10,
    "Flat Silver": 10,
    "Pearl Black": 10,
    "Pearl Dark Gray": 10,
    "Pearl Gold": 10,
    "Pearl Light Gold": 10,
    "Pearl Light Gray": 10,
    "Pearl Sand Blue": 10,
    "Pearl Very Light Gray": 10,
    "Pearl White": 10,
    "Reddish Gold": 10,
    "Satin Trans-Bright Green": 10,
    "Satin Trans-Brown": 10,
    "Satin Trans-Clear": 10,
    "Satin Trans-Dark Blue": 10,
    "Satin Trans-Dark Pink": 10,
    "Satin Trans-Light Blue": 10,
    "Satin Trans-Purple": 10,
    "Metallic Copper": 10,
    "Metallic Gold": 10,
    "Metallic Green": 10,
    "Metallic Silver": 10,
    "Glow In Dark Opaque": 10,
    "Glow In Dark Trans": 10,
    "Glow In Dark White": 10,
    "Milky White": 10,
    "Glitter Trans-Clear": 10,
    "Glitter Trans-Dark Pink": 10,
    "Glitter Trans-Light Blue": 10,
    "Glitter Trans-Neon Green": 10,
    "Glitter Trans-Orange": 10,
    "Glitter Trans-Purple": 10,
}

piece_3005 = {
    "aqua": 10,
    "black": 10,
    "blue": 10,
    "blue_violet": 10,
    "bright_green": 10,
    "bright_light_blue": 10,
    "bright_light_orange": 10,
    "bright_light_yellow": 10,
    "bright_pink": 10,
    "brown": 10,
    "clikits_lavender": 10,
    "coral": 10,
    "dark_azure": 10,
    "dark_blue": 10,
    "dark_blue_violet": 10,
    "dark_bluish_gray": 10,
    "dark_brown": 10,
    "dark_gray": 10,
    "dark_green": 10,
    "dark_nougat": 10,
    "dark_olive_green": 10,
    "dark_orange": 10,
    "dark_pink": 10,
    "dark_purple": 10,
    "dark_red": 10,
    "dark_salmon": 10,
    "dark_tan": 10,
    "dark_turquoise": 10,
    "dark_yellow": 10,
    "earth_orange": 10,
    "fabuland_brown": 10,
    "fabuland_lime": 10,
    "fabuland_orange": 10,
    "green": 10,
    "lavender": 10,
    "light_aqua": 10,
    "light_blue": 10,
    "light_bluish_gray": 10,
    "light_brown": 10,
    "light_gray": 10,
    "light_green": 10,
    "light_lilac": 10,
    "light_lime": 10,
    "light_nougat": 10,
    "light_orange": 10,
    "light_pink": 10,
    "light_purple": 10,
    "light_salmon": 10,
    "light_turquoise": 10,
    "light_violet": 10,
    "light_yellow": 10,
    "lilac": 10,
    "lime": 10,
    "little_robots_blue": 10,
    "maersk_blue": 10,
    "magenta": 10,
    "medium_azure": 10,
    "medium_blue": 10,
    "medium_brown": 10,
    "medium_dark_pink": 10,
    "medium_green": 10,
    "medium_lavender": 10,
    "medium_lime": 10,
    "medium_nougat": 10,
    "medium_orange": 10,
    "medium_tan": 10,
    "medium_violet": 10,
    "neon_green": 10,
    "neon_orange": 10,
    "neon_yellow": 10,
    "nougat": 10,
    "olive_green": 10,
    "orange": 10,
    "pink": 10,
    "purple": 10,
    "red": 10,
    "reddish_brown": 10,
    "rust": 10,
    "salmon": 10,
    "sand_blue": 10,
    "sand_green": 10,
    "sand_purple": 10,
    "sand_red": 10,
    "sky_blue": 10,
    "tan": 10,
    "very_light_bluish_gray": 10,
    "very_light_gray": 10,
    "very_light_orange": 10,
    "violet": 10,
    "white": 10,
    "yellow": 10,
    "yellowish_green": 10,
    "trans_aqua": 10,
    "trans_black": 10,
    "trans_bright_green": 10,
    "trans_brown": 10,
    "trans_clear": 10,
    "trans_dark_blue": 10,
    "trans_dark_pink": 10,
    "trans_green": 10,
    "trans_light_blue": 10,
    "trans_light_bright_green": 10,
    "trans_light_green": 10,
    "trans_light_orange": 10,
    "trans_light_purple": 10,
    "trans_medium_blue": 10,
    "trans_medium_purple": 10,
    "trans_neon_green": 10,
    "trans_neon_orange": 10,
    "trans_neon_yellow": 10,
    "trans_orange": 10,
    "trans_pink": 10,
    "trans_purple": 10,
    "trans_red": 10,
    "trans_yellow": 10,
    "chrome_antique_brass": 10,
    "chrome_black": 10,
    "chrome_blue": 10,
    "chrome_gold": 10,
    "chrome_green": 10,
    "chrome_pink": 10,
    "chrome_silver": 10,
    "bionicle_copper": 10,
    "bionicle_gold": 10,
    "bionicle_silver": 10,
    "copper": 10,
    "flat_dark_gold": 10,
    "flat_silver": 10,
    "pearl_black": 10,
    "pearl_dark_gray": 10,
    "pearl_gold": 10,
    "pearl_light_gold": 10,
    "pearl_light_gray": 10,
    "pearl_sand_blue": 10,
    "pearl_sand_purple": 10,
    "pearl_very_light_gray": 10,
    "pearl_white": 10,
    "reddish_copper": 10,
    "reddish_gold": 10,
    "satin_trans_bright_green": 10,
    "satin_trans_brown": 10,
    "satin_trans_clear": 10,
    "satin_trans_dark_blue": 10,
    "satin_trans_dark_pink": 10,
    "satin_trans_light_blue": 10,
    "satin_trans_purple": 10,
    "metallic_copper": 10,
    "metallic_gold": 10,
    "metallic_green": 10,
    "metallic_silver": 10,
    "glow_in_dark_opaque": 10,
    "glow_in_dark_trans": 10,
    "glow_in_dark_white": 10,
    "milky_white": 10,
    "glitter_trans_clear": 10,
    "glitter_trans_dark_pink": 10,
    "glitter_trans_light_blue": 10,
    "glitter_trans_neon_green": 10,
    "glitter_trans_orange": 10,
    "glitter_trans_purple": 10,
}

piece_3065 = {
    "aqua": 10,
    "black": 10,
    "blue": 10,
    "blue_violet": 10,
    "bright_green": 10,
    "bright_light_blue": 10,
    "bright_light_orange": 10,
    "bright_light_yellow": 10,
    "bright_pink": 10,
    "brown": 10,
    "clikits_lavender": 10,
    "coral": 10,
    "dark_azure": 10,
    "dark_blue": 10,
    "dark_blue_violet": 10,
    "dark_bluish_gray": 10,
    "dark_brown": 10,
    "dark_gray": 10,
    "dark_green": 10,
    "dark_nougat": 10,
    "dark_olive_green": 10,
    "dark_orange": 10,
    "dark_pink": 10,
    "dark_purple": 10,
    "dark_red": 10,
    "dark_salmon": 10,
    "dark_tan": 10,
    "dark_turquoise": 10,
    "dark_yellow": 10,
    "earth_orange": 10,
    "fabuland_brown": 10,
    "fabuland_lime": 10,
    "fabuland_orange": 10,
    "green": 10,
    "lavender": 10,
    "light_aqua": 10,
    "light_blue": 10,
    "light_bluish_gray": 10,
    "light_brown": 10,
    "light_gray": 10,
    "light_green": 10,
    "light_lime": 10,
    "light_nougat": 10,
    "light_orange": 10,
    "light_pink": 10,
    "light_purple": 10,
    "light_salmon": 10,
    "light_turquoise": 10,
    "light_violet": 10,
    "light_yellow": 10,
    "lilac": 10,
    "lime": 10,
    "maersk_blue": 10,
    "magenta": 10,
    "medium_azure": 10,
    "medium_blue": 10,
    "medium_brown": 10,
    "medium_dark_pink": 10,
    "medium_green": 10,
    "medium_lavender": 10,
    "medium_lime": 10,
    "medium_nougat": 10,
    "medium_orange": 10,
    "medium_tan": 10,
    "medium_violet": 10,
    "neon_green": 10,
    "neon_orange": 10,
    "neon_yellow": 10,
    "nougat": 10,
    "olive_green": 10,
    "orange": 10,
    "pink": 10,
    "purple": 10,
    "red": 10,
    "reddish_brown": 10,
    "rust": 10,
    "salmon": 10,
    "sand_blue": 10,
    "sand_green": 10,
    "sand_purple": 10,
    "sand_red": 10,
    "sky_blue": 10,
    "tan": 10,
    "very_light_bluish_gray": 10,
    "very_light_gray": 10,
    "very_light_orange": 10,
    "violet": 10,
    "white": 10,
    "yellow": 10,
    "yellowish_green": 10,
    "trans_aqua": 10,
    "trans_black": 10,
    "trans_bright_green": 10,
    "trans_brown": 10,
    "trans_clear": 10,
    "trans_dark_blue": 10,
    "trans_dark_pink": 10,
    "trans_green": 10,
    "trans_light_blue": 10,
    "trans_light_bright_green": 10,
    "trans_light_green": 10,
    "trans_light_orange": 10,
    "trans_light_purple": 10,
    "trans_medium_blue": 10,
    "trans_medium_purple": 10,
    "trans_neon_green": 10,
    "trans_neon_orange": 10,
    "trans_neon_yellow": 10,
    "trans_orange": 10,
    "trans_pink": 10,
    "trans_purple": 10,
    "trans_red": 10,
    "trans_yellow": 10,
    "chrome_antique_brass": 10,
    "chrome_black": 10,
    "chrome_blue": 10,
    "chrome_gold": 10,
    "chrome_green": 10,
    "chrome_pink": 10,
    "chrome_silver": 10,
    "bionicle_copper": 10,
    "bionicle_gold": 10,
    "bionicle_silver": 10,
    "copper": 10,
    "flat_dark_gold": 10,
    "flat_silver": 10,
    "pearl_black": 10,
    "pearl_dark_gray": 10,
    "pearl_gold": 10,
    "pearl_light_gold": 10,
    "pearl_light_gray": 10,
    "pearl_sand_blue": 10,
    "pearl_sand_purple": 10,
    "pearl_very_light_gray": 10,
    "pearl_white": 10,
    "reddish_copper": 10,
    "reddish_gold": 10,
    "satin_trans_bright_green": 10,
    "satin_trans_brown": 10,
    "satin_trans_clear": 10,
    "satin_trans_dark_blue": 10,
    "satin_trans_dark_pink": 10,
    "satin_trans_light_blue": 10,
    "satin_trans_purple": 10,
    "metallic_copper": 10,
    "metallic_gold": 10,
    "metallic_green": 10,
    "metallic_silver": 10,
    "glow_in_dark_opaque": 10,
    "glow_in_dark_trans": 10,
    "glow_in_dark_white": 10,
    "milky_white": 10,
    "glitter_trans_clear": 10,
    "glitter_trans_dark_pink": 10,
    "glitter_trans_light_blue": 10,
    "glitter_trans_neon_green": 10,
    "glitter_trans_orange": 10,
    "glitter_trans_purple": 10,
}

piece_3245b = {
    "aqua": 10,
    "black": 10,
    "blue": 10,
    "blue_violet": 10,
    "bright_green": 10,
    "bright_light_blue": 10,
    "bright_light_orange": 10,
    "bright_light_yellow": 10,
    "bright_pink": 10,
    "brown": 10,
    "clikits_lavender": 10,
    "dark_azure": 10,
    "dark_blue": 10,
    "dark_blue_violet": 10,
    "dark_bluish_gray": 10,
    "dark_brown": 10,
    "dark_gray": 10,
    "dark_green": 10,
    "dark_nougat": 10,
    "dark_orange": 10,
    "dark_pink": 10,
    "dark_purple": 10,
    "dark_red": 10,
    "dark_tan": 10,
    "dark_turquoise": 10,
    "dark_yellow": 10,
    "earth_orange": 10,
    "fabuland_brown": 10,
    "fabuland_orange": 10,
    "green": 10,
    "lavender": 10,
    "light_blue": 10,
    "light_bluish_gray": 10,
    "light_brown": 10,
    "light_gray": 10,
    "light_green": 10,
    "light_lime": 10,
    "light_nougat": 10,
    "light_orange": 10,
    "light_pink": 10,
    "light_salmon": 10,
    "light_yellow": 10,
    "lilac": 10,
    "lime": 10,
    "maersk_blue": 10,
    "magenta": 10,
    "medium_azure": 10,
    "medium_blue": 10,
    "medium_brown": 10,
    "medium_dark_pink": 10,
    "medium_green": 10,
    "medium_lavender": 10,
    "medium_lime": 10,
    "medium_nougat": 10,
    "medium_orange": 10,
    "medium_tan": 10,
    "neon_green": 10,
    "neon_orange": 10,
    "neon_yellow": 10,
    "nougat": 10,
    "olive_green": 10,
    "orange": 10,
    "pink": 10,
    "purple": 10,
    "red": 10,
    "reddish_brown": 10,
    "rust": 10,
    "salmon": 10,
    "sand_blue": 10,
    "sand_green": 10,
    "sand_purple": 10,
    "sky_blue": 10,
    "tan": 10,
    "very_light_bluish_gray": 10,
    "very_light_gray": 10,
    "very_light_orange": 10,
    "violet": 10,
    "white": 10,
    "yellow": 10,
    "yellowish_green": 10,
    "trans_aqua": 10,
    "trans_black": 10,
    "trans_brown": 10,
    "trans_clear": 10,
    "trans_dark_blue": 10,
    "trans_light_blue": 10,
    "trans_medium_blue": 10,
    "trans_neon_orange": 10,
    "trans_red": 10,
    "trans_yellow": 10,
    "chrome_antique_brass": 10,
    "chrome_gold": 10,
    "chrome_green": 10,
    "chrome_silver": 10,
    "copper": 10,
    "flat_silver": 10,
    "pearl_black": 10,
    "pearl_dark_gray": 10,
    "pearl_gold": 10,
    "pearl_light_gray": 10,
    "pearl_very_light_gray": 10,
    "pearl_white": 10,
    "metallic_copper": 10,
    "metallic_silver": 10,
    "glow_in_dark_white": 10,
    "glitter_trans_clear": 10
}

piece_3245c = {
    "Aqua": 10,
    "Black": 10,
    "Blue": 10,
    "Blue-Violet": 10,
    "Bright Green": 10,
    "Bright Light Blue": 10,
    "Bright Light Orange": 10,
    "Bright Light Yellow": 10,
    "Bright Pink": 10,
    "Brown": 10,
    "Clikits Lavender": 10,
    "Dark Azure": 10,
    "Dark Blue": 10,
    "Dark Blue-Violet": 10,
    "Dark Bluish Gray": 10,
    "Dark Brown": 10,
    "Dark Gray": 10,
    "Dark Green": 10,
    "Dark Nougat": 10,
    "Dark Orange": 10,
    "Dark Pink": 10,
    "Dark Purple": 10,
    "Dark Red": 10,
    "Dark Tan": 10,
    "Dark Turquoise": 10,
    "Dark Yellow": 10,
    "Earth Orange": 10,
    "Fabuland Brown": 10,
    "Fabuland Orange": 10,
    "Green": 10,
    "Lavender": 10,
    "Light Aqua": 10,
    "Light Blue": 10,
    "Light Bluish Gray": 10,
    "Light Brown": 10,
    "Light Gray": 10,
    "Light Green": 10,
    "Light Nougat": 10,
    "Light Pink": 10,
    "Light Purple": 10,
    "Light Salmon": 10,
    "Light Turquoise": 10,
    "Light Yellow": 10,
    "Lime": 10,
    "Maersk Blue": 10,
    "Magenta": 10,
    "Medium Azure": 10,
    "Medium Blue": 10,
    "Medium Brown": 10,
    "Medium Dark Pink": 10,
    "Medium Green": 10,
    "Medium Lavender": 10,
    "Medium Lime": 10,
    "Medium Nougat": 10,
    "Medium Orange": 10,
    "Medium Tan": 10,
    "Medium Violet": 10,
    "Nougat": 10,
    "Olive Green": 10,
    "Orange": 10,
    "Pink": 10,
    "Purple": 10,
    "Red": 10,
    "Reddish Brown": 10,
    "Rust": 10,
    "Salmon": 10,
    "Sand Blue": 10,
    "Sand Green": 10,
    "Sand Red": 10,
    "Sky Blue": 10,
    "Tan": 10,
    "Very Light Bluish Gray": 10,
    "Very Light Gray": 10,
    "Very Light Orange": 10,
    "Violet": 10,
    "White": 10,
    "Yellow": 10,
    "Trans-Aqua": 10,
    "Trans-Black (2023)": 10,
    "Trans-Brown (Old Trans-Black)": 10,
    "Trans-Clear": 10,
    "Trans-Dark Blue": 10,
    "Trans-Light Blue": 10,
    "Trans-Medium Blue": 10,
    "Trans-Neon Green": 10,
    "Trans-Orange": 10,
    "Trans-Red": 10,
    "Trans-Yellow": 10,
    "Chrome Black": 10,
    "Chrome Gold": 10,
    "Chrome Silver": 10,
    "Copper": 10,
    "Flat Silver": 10,
    "Pearl Black": 10,
    "Pearl Dark Gray": 10,
    "Pearl Gold": 10,
    "Pearl Light Gray": 10,
    "Pearl Sand Blue": 10,
    "Pearl White": 10,
    "Metallic Gold": 10,
    "Metallic Silver": 10,
    "Glow In Dark White": 10,
    "Milky White": 10,
}

piece_3622 = {
    "aqua": 10,
    "black": 10,
    "blue": 10,
    "blue_violet": 10,
    "bright_green": 10,
    "bright_light_blue": 10,
    "bright_light_orange": 10,
    "bright_light_yellow": 10,
    "bright_pink": 10,
    "brown": 10,
    "clikits_lavender": 10,
    "coral": 10,
    "dark_azure": 10,
    "dark_blue": 10,
    "dark_blue_violet": 10,
    "dark_bluish_gray": 10,
    "dark_brown": 10,
    "dark_gray": 10,
    "dark_green": 10,
    "dark_nougat": 10,
    "dark_olive_green": 10,
    "dark_orange": 10,
    "dark_pink": 10,
    "dark_purple": 10,
    "dark_red": 10,
    "dark_salmon": 10,
    "dark_tan": 10,
    "dark_turquoise": 10,
    "dark_yellow": 10,
    "earth_orange": 10,
    "fabuland_brown": 10,
    "fabuland_lime": 10,
    "fabuland_orange": 10,
    "green": 10,
    "lavender": 10,
    "light_aqua": 10,
    "light_blue": 10,
    "light_bluish_gray": 10,
    "light_brown": 10,
    "light_gray": 10,
    "light_green": 10,
    "light_lime": 10,
    "light_nougat": 10,
    "light_orange": 10,
    "light_pink": 10,
    "light_purple": 10,
    "light_salmon": 10,
    "light_turquoise": 10,
    "light_violet": 10,
    "light_yellow": 10,
    "lilac": 10,
    "lime": 10,
    "little_robots_blue": 10,
    "maersk_blue": 10,
    "magenta": 10,
    "medium_azure": 10,
    "medium_blue": 10,
    "medium_brown": 10,
    "medium_dark_pink": 10,
    "medium_green": 10,
    "medium_lavender": 10,
    "medium_lime": 10,
    "medium_nougat": 10,
    "medium_orange": 10,
    "medium_tan": 10,
    "medium_violet": 10,
    "neon_green": 10,
    "neon_orange": 10,
    "neon_yellow": 10,
    "nougat": 10,
    "olive_green": 10,
    "orange": 10,
    "pink": 10,
    "purple": 10,
    "red": 10,
    "reddish_brown": 10,
    "rust": 10,
    "salmon": 10,
    "sand_blue": 10,
    "sand_green": 10,
    "sand_purple": 10,
    "sand_red": 10,
    "sky_blue": 10,
    "tan": 10,
    "very_light_bluish_gray": 10,
    "very_light_gray": 10,
    "very_light_orange": 10,
    "violet": 10,
    "white": 10,
    "yellow": 10,
    "yellowish_green": 10,
    "trans_aqua": 10,
    "trans_black": 10,
    "trans_bright_green": 10,
    "trans_brown": 10,
    "trans_clear": 10,
    "trans_dark_blue": 10,
    "trans_dark_pink": 10,
    "trans_green": 10,
    "trans_light_blue": 10,
    "trans_light_bright_green": 10,
    "trans_light_green": 10,
    "trans_light_orange": 10,
    "trans_light_purple": 10,
    "trans_medium_blue": 10,
    "trans_medium_purple": 10,
    "trans_neon_green": 10,
    "trans_neon_orange": 10,
    "trans_neon_yellow": 10,
    "trans_orange": 10,
    "trans_pink": 10,
    "trans_purple": 10,
    "trans_red": 10,
    "trans_yellow": 10,
    "chrome_antique_brass": 10,
    "chrome_black": 10,
    "chrome_blue": 10,
    "chrome_gold": 10,
    "chrome_green": 10,
    "chrome_pink": 10,
    "chrome_silver": 10,
    "bionicle_copper": 10,
    "bionicle_gold": 10,
    "bionicle_silver": 10,
    "copper": 10,
    "flat_dark_gold": 10,
    "flat_silver": 10,
    "pearl_black": 10,
    "pearl_dark_gray": 10,
    "pearl_gold": 10,
    "pearl_light_gold": 10,
    "pearl_light_gray": 10,
    "pearl_sand_blue": 10,
    "pearl_very_light_gray": 10,
    "pearl_white": 10,
    "reddish_gold": 10,
    "satin_trans_bright_green": 10,
    "satin_trans_brown": 10,
    "satin_trans_clear": 10,
    "satin_trans_dark_blue": 10,
    "satin_trans_dark_pink": 10,
    "satin_trans_light_blue": 10,
    "satin_trans_purple": 10,
    "metallic_copper": 10,
    "metallic_gold": 10,
    "metallic_green": 10,
    "metallic_silver": 10,
    "glow_in_dark_opaque": 10,
    "glow_in_dark_trans": 10,
    "glow_in_dark_white": 10,
    "milky_white": 10,
    "glitter_trans_clear": 10,
    "glitter_trans_dark_pink": 10,
    "glitter_trans_light_blue": 10,
    "glitter_trans_neon_green": 10,
    "glitter_trans_orange": 10,
    "glitter_trans_purple": 10
}

piece_3755 = {
    "aqua": 10,
    "black": 10,
    "blue": 10,
    "blue_violet": 10,
    "bright_green": 10,
    "bright_light_blue": 10,
    "bright_light_orange": 10,
    "bright_light_yellow": 10,
    "bright_pink": 10,
    "brown": 10,
    "clikits_lavender": 10,
    "coral": 10,
    "dark_azure": 10,
    "dark_blue": 10,
    "dark_blue_violet": 10,
    "dark_bluish_gray": 10,
    "dark_brown": 10,
    "dark_gray": 10,
    "dark_green": 10,
    "dark_olive_green": 10,
    "dark_orange": 10,
    "dark_pink": 10,
    "dark_purple": 10,
    "dark_red": 10,
    "dark_tan": 10,
    "dark_yellow": 10,
    "earth_orange": 10,
    "fabuland_brown": 10,
    "green": 10,
    "lavender": 10,
    "light_blue": 10,
    "light_bluish_gray": 10,
    "light_brown": 10,
    "light_gray": 10,
    "light_lime": 10,
    "light_nougat": 10,
    "light_orange": 10,
    "light_yellow": 10,
    "lime": 10,
    "medium_azure": 10,
    "medium_blue": 10,
    "medium_brown": 10,
    "medium_green": 10,
    "medium_lime": 10,
    "medium_nougat": 10,
    "medium_tan": 10,
    "neon_orange": 10,
    "neon_yellow": 10,
    "nougat": 10,
    "olive_green": 10,
    "orange": 10,
    "pink": 10,
    "purple": 10,
    "red": 10,
    "reddish_brown": 10,
    "rust": 10,
    "sand_blue": 10,
    "sand_green": 10,
    "sky_blue": 10,
    "tan": 10,
    "very_light_bluish_gray": 10,
    "very_light_gray": 10,
    "white": 10,
    "yellow": 10,
    "yellowish_green": 10,
    "trans_brown": 10,
    "trans_clear": 10,
    "trans_dark_blue": 10,
    "trans_light_blue": 10,
    "trans_medium_blue": 10,
    "trans_neon_orange": 10,
    "trans_purple": 10,
    "trans_red": 10,
    "chrome_antique_brass": 10,
    "chrome_black": 10,
    "chrome_gold": 10,
    "chrome_silver": 10,
    "copper": 10,
    "flat_silver": 10,
    "pearl_black": 10,
    "pearl_dark_gray": 10,
    "pearl_gold": 10,
    "pearl_light_gray": 10,
    "pearl_white": 10,
    "metallic_silver": 10,
    "glow_in_dark_white": 10,
}

piece_14716 = {
    "aqua": 10,
    "black": 10,
    "blue": 10,
    "blue_violet": 10,
    "bright_green": 10,
    "bright_light_blue": 10,
    "bright_light_orange": 10,
    "bright_light_yellow": 10,
    "bright_pink": 10,
    "brown": 10,
    "clikits_lavender": 10,
    "coral": 10,
    "dark_azure": 10,
    "dark_blue": 10,
    "dark_blue_violet": 10,
    "dark_bluish_gray": 10,
    "dark_brown": 10,
    "dark_gray": 10,
    "dark_green": 10,
    "dark_nougat": 10,
    "dark_orange": 10,
    "dark_pink": 10,
    "dark_purple": 10,
    "dark_red": 10,
    "dark_tan": 10,
    "dark_turquoise": 10,
    "dark_yellow": 10,
    "earth_orange": 10,
    "fabuland_brown": 10,
    "fabuland_lime": 10,
    "fabuland_orange": 10,
    "green": 10,
    "lavender": 10,
    "light_aqua": 10,
    "light_blue": 10,
    "light_bluish_gray": 10,
    "light_brown": 10,
    "light_gray": 10,
    "light_green": 10,
    "light_lime": 10,
    "light_nougat": 10,
    "light_orange": 10,
    "light_pink": 10,
    "light_purple": 10,
    "light_salmon": 10,
    "light_turquoise": 10,
    "light_yellow": 10,
    "lilac": 10,
    "lime": 10,
    "maersk_blue": 10,
    "magenta": 10,
    "medium_azure": 10,
    "medium_blue": 10,
    "medium_brown": 10,
    "medium_dark_pink": 10,
    "medium_green": 10,
    "medium_lavender": 10,
    "medium_lime": 10,
    "medium_nougat": 10,
    "medium_orange": 10,
    "medium_tan": 10,
    "medium_violet": 10,
    "neon_green": 10,
    "neon_orange": 10,
    "neon_yellow": 10,
    "nougat": 10,
    "olive_green": 10,
    "orange": 10,
    "pink": 10,
    "purple": 10,
    "red": 10,
    "reddish_brown": 10,
    "rust": 10,
    "salmon": 10,
    "sand_blue": 10,
    "sand_green": 10,
    "sand_purple": 10,
    "sand_red": 10,
    "sky_blue": 10,
    "tan": 10,
    "very_light_bluish_gray": 10,
    "very_light_gray": 10,
    "very_light_orange": 10,
    "violet": 10,
    "white": 10,
    "yellow": 10,
    "yellowish_green": 10,
    "trans_aqua": 10,
    "trans_black": 10,
    "trans_brown": 10,
    "trans_clear": 10,
    "trans_dark_blue": 10,
    "trans_light_blue": 10,
    "trans_light_orange": 10,
    "trans_light_purple": 10,
    "trans_medium_blue": 10,
    "trans_neon_green": 10,
    "trans_neon_orange": 10,
    "trans_neon_yellow": 10,
    "trans_orange": 10,
    "trans_purple": 10,
    "trans_yellow": 10,
    "chrome_antique_brass": 10,
    "chrome_black": 10,
    "chrome_blue": 10,
    "chrome_gold": 10,
    "chrome_pink": 10,
    "chrome_silver": 10,
    "bionicle_gold": 10,
    "copper": 10,
    "flat_silver": 10,
    "pearl_black": 10,
    "pearl_dark_gray": 10,
    "pearl_gold": 10,
    "pearl_light_gray": 10,
    "pearl_very_light_gray": 10,
    "pearl_white": 10,
    "metallic_copper": 10,
    "metallic_gold": 10,
    "metallic_silver": 10,
    "glow_in_dark_white": 10,
    "milky_white": 10,
    "glitter_trans_purple": 10,
}

piece_46212 = {
    "aqua": 10,
    "black": 10,
    "blue": 10,
    "blue_violet": 10,
    "bright_green": 10,
    "bright_light_blue": 10,
    "bright_light_orange": 10,
    "bright_light_yellow": 10,
    "bright_pink": 10,
    "brown": 10,
    "clikits_lavender": 10,
    "coral": 10,
    "dark_azure": 10,
    "dark_blue": 10,
    "dark_blue_violet": 10,
    "dark_bluish_gray": 10,
    "dark_brown": 10,
    "dark_gray": 10,
    "dark_green": 10,
    "dark_nougat": 10,
    "dark_orange": 10,
    "dark_pink": 10,
    "dark_purple": 10,
    "dark_red": 10,
    "dark_tan": 10,
    "dark_turquoise": 10,
    "dark_yellow": 10,
    "fabuland_brown": 10,
    "fabuland_orange": 10,
    "green": 10,
    "lavender": 10,
    "light_aqua": 10,
    "light_blue": 10,
    "light_bluish_gray": 10,
    "light_brown": 10,
    "light_gray": 10,
    "light_lime": 10,
    "light_nougat": 10,
    "light_orange": 10,
    "light_pink": 10,
    "light_turquoise": 10,
    "light_violet": 10,
    "light_yellow": 10,
    "lime": 10,
    "maersk_blue": 10,
    "magenta": 10,
    "medium_azure": 10,
    "medium_blue": 10,
    "medium_brown": 10,
    "medium_green": 10,
    "medium_lavender": 10,
    "medium_lime": 10,
    "medium_nougat": 10,
    "medium_orange": 10,
    "medium_tan": 10,
    "neon_orange": 10,
    "neon_yellow": 10,
    "nougat": 10,
    "olive_green": 10,
    "orange": 10,
    "pink": 10,
    "purple": 10,
    "red": 10,
    "reddish_brown": 10,
    "rust": 10,
    "sand_blue": 10,
    "sand_green": 10,
    "sky_blue": 10,
    "tan": 10,
    "very_light_bluish_gray": 10,
    "very_light_gray": 10,
    "very_light_orange": 10,
    "white": 10,
    "yellow": 10,
    "trans_aqua": 10,
    "trans_black": 10,
    "trans_bright_green": 10,
    "trans_brown": 10,
    "trans_clear": 10,
    "trans_dark_blue": 10,
    "trans_dark_pink": 10,
    "trans_green": 10,
    "trans_light_blue": 10,
    "trans_light_bright_green": 10,
    "trans_light_orange": 10,
    "trans_light_purple": 10,
    "trans_medium_blue": 10,
    "trans_medium_purple": 10,
    "trans_neon_green": 10,
    "trans_neon_orange": 10,
    "trans_orange": 10,
    "trans_purple": 10,
    "trans_red": 10,
    "trans_yellow": 10,
    "chrome_black": 10,
    "chrome_blue": 10,
    "chrome_gold": 10,
    "chrome_silver": 10,
    "bionicle_silver": 10,
    "copper": 10,
    "flat_silver": 10,
    "pearl_black": 10,
    "pearl_dark_gray": 10,
    "pearl_gold": 10,
    "pearl_light_gold": 10,
    "pearl_very_light_gray": 10,
    "pearl_white": 10,
    "satin_trans_clear": 10,
    "satin_trans_light_blue": 10,
    "metallic_green": 10,
    "metallic_silver": 10,
    "glitter_trans_clear": 10,
}

piece_49311 = {
    "aqua": 10,
    "black": 10,
    "blue": 10,
    "blue_violet": 10,
    "bright_green": 10,
    "bright_light_blue": 10,
    "bright_light_orange": 10,
    "bright_light_yellow": 10,
    "brown": 10,
    "clikits_lavender": 10,
    "coral": 10,
    "dark_azure": 10,
    "dark_blue": 10,
    "dark_blue_violet": 10,
    "dark_bluish_gray": 10,
    "dark_brown": 10,
    "dark_gray": 10,
    "dark_green": 10,
    "dark_orange": 10,
    "dark_pink": 10,
    "dark_purple": 10,
    "dark_red": 10,
    "dark_tan": 10,
    "dark_turquoise": 10,
    "dark_yellow": 10,
    "earth_orange": 10,
    "fabuland_brown": 10,
    "green": 10,
    "lavender": 10,
    "light_blue": 10,
    "light_bluish_gray": 10,
    "light_brown": 10,
    "light_gray": 10,
    "light_lime": 10,
    "light_nougat": 10,
    "light_pink": 10,
    "light_violet": 10,
    "light_yellow": 10,
    "lime": 10,
    "magenta": 10,
    "medium_azure": 10,
    "medium_blue": 10,
    "medium_brown": 10,
    "medium_dark_pink": 10,
    "medium_green": 10,
    "medium_lavender": 10,
    "medium_lime": 10,
    "medium_nougat": 10,
    "medium_orange": 10,
    "medium_tan": 10,
    "neon_green": 10,
    "neon_orange": 10,
    "neon_yellow": 10,
    "nougat": 10,
    "olive_green": 10,
    "orange": 10,
    "pink": 10,
    "purple": 10,
    "red": 10,
    "reddish_brown": 10,
    "rust": 10,
    "sand_blue": 10,
    "sand_green": 10,
    "sand_red": 10,
    "sky_blue": 10,
    "tan": 10,
    "very_light_bluish_gray": 10,
    "very_light_gray": 10,
    "very_light_orange": 10,
    "violet": 10,
    "white": 10,
    "yellow": 10,
    "yellowish_green": 10,
    "trans_black": 10,
    "trans_brown": 10,
    "trans_clear": 10,
    "trans_dark_blue": 10,
    "trans_dark_pink": 10,
    "trans_green": 10,
    "trans_light_blue": 10,
    "trans_medium_blue": 10,
    "trans_neon_yellow": 10,
    "trans_purple": 10,
    "trans_red": 10,
    "trans_yellow": 10,
    "chrome_antique_brass": 10,
    "chrome_black": 10,
    "chrome_gold": 10,
    "chrome_silver": 10,
    "copper": 10,
    "flat_dark_gold": 10,
    "flat_silver": 10,
    "pearl_black": 10,
    "pearl_dark_gray": 10,
    "pearl_gold": 10,
    "pearl_light_gray": 10,
    "metallic_gold": 10,
    "metallic_green": 10,
    "metallic_silver": 10,
}

piece_87615 = {
    "black": 10,
    "blue": 10,
    "bright_light_blue": 10,
    "brown": 10,
    "dark_blue": 10,
    "dark_bluish_gray": 10,
    "dark_brown": 10,
    "dark_gray": 10,
    "dark_green": 10,
    "dark_purple": 10,
    "dark_tan": 10,
    "green": 10,
    "light_bluish_gray": 10,
    "light_brown": 10,
    "light_gray": 10,
    "medium_nougat": 10,
    "medium_orange": 10,
    "orange": 10,
    "red": 10,
    "reddish_brown": 10,
    "sand_blue": 10,
    "tan": 10,
    "very_light_bluish_gray": 10,
    "very_light_gray": 10,
    "white": 10,
    "yellow": 10,
    "trans_light_blue": 10,
    "trans_light_bright_green": 10,
    "pearl_dark_gray": 10,
}



def calculate_total():
    selected_piece = piece_entry.get()
    selected_color = color_entry.get()

    if selected_piece in ["2038", "2039", "2335", "2336", "2338", "2339", "2340", "2341", "2342", "3001", "3004", "3005", "772", "2453a", "2453b", "2454", "3245b", "3245c", "22886", "3004", "3305", "3065", "3622", "3755", "14716", "46212", "49311", "87615"]:
        total = globals()[f"piece_{selected_piece}"].get(selected_color, 0)
    else:
        result_label.config(text=f"Piece {selected_piece} not found in inventory", foreground="red")
        return

    result_label.config(text=f"Total quantity of {selected_color} {selected_piece}: {total}", foreground="green")

def lookup_color_total():
    selected_color = color_entry.get()
    total = 0

    for piece_number in ["2038", "2039", "2335", "2336", "2338", "2339", "2340", "2341", "2342", "3001", "3004", "3005", "772", "2453a", "2453b", "2454", "3245b", "3245c", "22886", "3004", "3005", "3065", "3622", "3755", "14716", "46212", "49311", "87615"]:
        total += globals()[f"piece_{piece_number}"].get(selected_color, 0)

    result_label.config(text=f"Total quantity of {selected_color} for all pieces: {total}", foreground="blue")

# ... rest of the code ...


# Create the main window
window = tk.Tk()
window.title("Inventory Calculator")
window.geometry("400x350")  # Set window size

# Create and place widgets with some styling
style = ttk.Style()
style.configure("TButton", padding=10, font=('Helvetica', 12))
style.configure("TLabel", padding=5, font=('Helvetica', 12))

piece_label = ttk.Label(window, text="Enter the piece number:")
piece_label.pack(pady=10)

piece_entry = ttk.Entry(window, font=('Helvetica', 12))
piece_entry.pack(pady=10)

color_label = ttk.Label(window, text="Enter the color:")
color_label.pack(pady=10)

color_entry = ttk.Entry(window, font=('Helvetica', 12))
color_entry.pack(pady=10)

calculate_button = ttk.Button(window, text="Calculate Total", command=calculate_total)
calculate_button.pack(pady=10)

lookup_button = ttk.Button(window, text="Lookup Color Total", command=lookup_color_total)
lookup_button.pack(pady=10)

result_label = ttk.Label(window, text="", font=('Helvetica', 12))
result_label.pack(pady=10)

# Start the Tkinter event loop
window.mainloop()