#Lego pieces inventory
piece_2038 = {
    "black": 10,
    "blue": 10,
    "brown": 10,
    "dark_green": 10,
    "dark_pink": 10,
    "green": 10,
    "light_gray": 10,
    "red": 10,
    "reddish_brown": 10,
    "tan": 10,
    "white": 10,
    "yellow": 10,
    "chrome_silver": 10,
    "flat_silver": 10
}

piece_2039 = {
    "black": 10,
    "blue": 10,
    "bright_light_blue": 10,
    "brown": 10,
    "dark_blue": 10,
    "dark_bluish_gray": 10,
    "dark_brown": 10,
    "dark_gray": 10,
    "dark_green": 10,
    "dark_purple": 10,
    "dark_tan": 10,
    "dark_turquoise": 10,
    "green": 10,
    "light_bluish_gray": 10,
    "light_gray": 10,
    "light_turquoise": 10,
    "medium_lavender": 10,
    "pink": 10,
    "red": 10,
    "sand_blue": 10,
    "sand_green": 10,
    "tan": 10,
    "violet": 10,
    "white": 10,
    "yellow": 10,
    "trans_red": 10,
    "flat_silver": 10,
    "pearl_black": 10,
    "pearl_dark_gray": 10,
    "reddish_gold": 10,
    "satin_trans_clear": 10
}

piece_2335 = {
    "aqua": 10,
    "black": 10,
    "blue": 10,
    "bright_green": 10,
    "bright_light_blue": 10,
    "bright_light_orange": 10,
    "bright_light_yellow": 10,
    "bright_pink": 10,
    "brown": 10,
    "dark_azure": 10,
    "dark_blue": 10,
    "dark_blue_violet": 10,
    "dark_bluish_gray": 10,
    "dark_brown": 10,
    "dark_gray": 10,
    "dark_green": 10,
    "dark_orange": 10,
    "dark_pink": 10,
    "dark_purple": 10,
    "dark_red": 10,
    "dark_tan": 10,
    "dark_turquoise": 10,
    "dark_yellow": 10,
    "earth_orange": 10,
    "green": 10,
    "light_aqua": 10,
    "light_bluish_gray": 10,
    "light_brown": 10,
    "light_gray": 10,
    "light_nougat": 10,
    "light_pink": 10,
    "light_purple": 10,
    "light_turquoise": 10,
    "light_yellow": 10,
    "lime": 10,
    "maersk_blue": 10,
    "magenta": 10,
    "medium_azure": 10,
    "medium_blue": 10,
    "medium_lavender": 10,
    "medium_nougat": 10,
    "medium_orange": 10,
    "medium_violet": 10,
    "neon_orange": 10,
    "nougat": 10,
    "olive_green": 10,
    "orange": 10,
    "pink": 10,
    "purple": 10,
    "red": 10,
    "reddish_brown": 10,
    "rust": 10,
    "sand_blue": 10,
    "sand_green": 10,
    "sky_blue": 10,
    "tan": 10,
    "very_light_bluish_gray": 10,
    "very_light_gray": 10,
    "white": 10,
    "yellow": 10,
    "yellowish_green": 10,
    "trans_aqua": 10,
    "trans_brown": 10,
    "trans_clear": 10,
    "trans_dark_blue": 10,
    "trans_light_blue": 10,
    "trans_neon_green": 10,
    "trans_purple": 10,
    "trans_red": 10,
    "chrome_black": 10,
    "chrome_blue": 10,
    "chrome_silver": 10,
    "flat_silver": 10,
    "pearl_dark_gray": 10,
    "pearl_gold": 10,
    "pearl_light_gray": 10,
    "metallic_silver": 10
}

piece_2336 = {
    "black": 16,
    "blue": 8,
    "dark_bluish_gray": 1,
    "dark_gray": 1,
    "green": 2,
    "light_gray": 4,
    "orange": 214,
    "red": 10,
    "tan": 3,
    "white": 14,
    "yellow": 2
}

piece_2338 = {
    "black": 556,
    "blue": 1,
    "brown": 1,
    "green": 1,
    "orange": 3,
    "red": 1025,
    "tan": 2,
    "white": 533,
    "yellow": 2,
    "trans_clear": 2
}

piece_2339 = {
    "black": 28729,
    "blue": 109,
    "bright_green": 1,
    "bright_light_blue": 1,
    "bright_light_orange": 1,
    "bright_light_yellow": 2,
    "brown": 2906,
    "dark_azure": 1,
    "dark_blue": 6315,
    "dark_blue_violet": 1,
    "dark_bluish_gray": 17715,
    "dark_brown": 6488,
    "dark_gray": 278,
    "dark_green": 13,
    "dark_nougat": 2,
    "dark_orange": 9,
    "dark_pink": 1,
    "dark_purple": 62,
    "dark_red": 35,
    "dark_tan": 829,
    "dark_turquoise": 141,
    "earth_orange": 1,
    "fabuland_brown": 15,
    "green": 301,
    "lavender": 128,
    "light_bluish_gray": 32947,
    "light_brown": 9,
    "light_gray": 4904,
    "light_nougat": 2,
    "light_orange": 1,
    "light_pink": 2,
    "light_yellow": 42,
    "medium_blue": 5,
    "medium_brown": 3,
    "medium_lavender": 201,
    "medium_nougat": 750,
    "medium_tan": 1,
    "nougat": 1,
    "olive_green": 3,
    "orange": 4,
    "purple": 1,
    "red": 3342,
    "reddish_brown": 31104,
    "salmon": 1,
    "sand_green": 11,
    "tan": 11701,
    "very_light_bluish_gray": 13,
    "very_light_gray": 5,
    "very_light_orange": 1,
    "white": 10031,
    "yellow": 2214,
    "trans_dark_blue": 2,
    "trans_green": 1,
    "trans_light_orange": 2,
    "chrome_gold": 1,
    "pearl_dark_gray": 7,
    "pearl_gold": 4
}

piece_2340 = {
    "black": 6311,
    "blue": 2849,
    "bright_green": 1,
    "bright_light_blue": 1,
    "bright_light_orange": 121,
    "bright_pink": 1,
    "clikits_lavender": 2,
    "dark_azure": 1,
    "dark_blue": 326,
    "dark_bluish_gray": 1478,
    "dark_gray": 287,
    "dark_green": 5,
    "dark_orange": 204,
    "dark_pink": 1,
    "dark_purple": 2,
    "dark_red": 129,
    "dark_tan": 2,
    "dark_turquoise": 382,
    "green": 11,
    "light_aqua": 1,
    "light_bluish_gray": 1657,
    "light_gray": 1129,
    "magenta": 131,
    "medium_azure": 381,
    "medium_lime": 1,
    "medium_nougat": 1,
    "olive_green": 1,
    "orange": 313,
    "red": 2694,
    "reddish_brown": 78,
    "sand_blue": 1,
    "sand_green": 1,
    "sky_blue": 1,
    "tan": 6,
    "very_light_bluish_gray": 10,
    "white": 5980,
    "yellow": 580,
    "trans_clear": 29,
    "trans_green": 1,
    "trans_neon_yellow": 1,
    "trans_orange": 1,
    "pearl_dark_gray": 1,
    "milky_white": 1
}

piece_2341 = {
    "black": 4719,
    "blue": 30,
    "bright_green": 1,
    "bright_light_orange": 3,
    "brown": 46,
    "dark_azure": 2,
    "dark_blue": 25,
    "dark_blue_violet": 1,
    "dark_bluish_gray": 11866,
    "dark_brown": 23,
    "dark_gray": 58,
    "dark_green": 7,
    "dark_orange": 2,
    "dark_pink": 2,
    "dark_purple": 128,
    "dark_red": 1072,
    "dark_tan": 11,
    "earth_orange": 16,
    "fabuland_brown": 16,
    "fabuland_orange": 1,
    "green": 9,
    "light_aqua": 23,
    "light_blue": 1,
    "light_bluish_gray": 24589,
    "light_brown": 4,
    "light_gray": 1835,
    "light_green": 16,
    "light_nougat": 6,
    "lime": 3,
    "magenta": 1,
    "medium_azure": 312,
    "medium_blue": 4,
    "medium_nougat": 2,
    "medium_orange": 1,
    "olive_green": 2,
    "orange": 27,
    "purple": 1,
    "red": 2086,
    "reddish_brown": 75,
    "rust": 2,
    "sand_blue": 2,
    "sand_green": 11,
    "tan": 2740,
    "very_light_bluish_gray": 15,
    "very_light_gray": 5,
    "white": 4822,
    "yellow": 207,
    "trans_bright_green": 2,
    "chrome_black": 2,
    "chrome_gold": 2,
    "chrome_silver": 6,
    "copper": 4,
    "flat_silver": 3,
    "pearl_dark_gray": 3,
    "pearl_gold": 2,
    "metallic_silver": 3,
    "glow_in_dark_white": 4,
}

piece_2342 = {
    "black": 3751,
    "blue": 745,
    "bright_light_yellow": 2,
    "brown": 15,
    "dark_bluish_gray": 96,
    "dark_brown": 21,
    "dark_gray": 846,
    "dark_green": 1,
    "dark_red": 7,
    "dark_tan": 20,
    "dark_turquoise": 339,
    "green": 31,
    "light_bluish_gray": 78,
    "light_gray": 1663,
    "light_nougat": 1,
    "orange": 1,
    "red": 405,
    "reddish_brown": 6,
    "sand_blue": 1,
    "tan": 29,
    "very_light_bluish_gray": 3,
    "white": 2703,
    "yellow": 764,
    "flat_silver": 2,
    "pearl_black": 1,
    "pearl_dark_gray": 7
}

piece_3245b = {
    "aqua": 5,
    "black": 4867,
    "blue": 199,
    "blue_violet": 8,
    "bright_green": 37,
    "bright_light_blue": 11,
    "bright_light_orange": 52,
    "bright_light_yellow": 25,
    "bright_pink": 2,
    "brown": 123,
    "clikits_lavender": 3,
    "dark_azure": 12,
    "dark_blue": 1303,
    "dark_blue_violet": 12,
    "dark_bluish_gray": 9121,
    "dark_brown": 106,
    "dark_gray": 425,
    "dark_green": 67,
    "dark_nougat": 1,
    "dark_orange": 44,
    "dark_pink": 4,
    "dark_purple": 10,
    "dark_red": 135,
    "dark_tan": 130,
    "dark_turquoise": 533,
    "dark_yellow": 6,
    "earth_orange": 4,
    "fabuland_brown": 20,
    "fabuland_orange": 9,
    "green": 81,
    "lavender": 3,
    "light_blue": 6,
    "light_bluish_gray": 15937,
    "light_brown": 50,
    "light_gray": 4975,
    "light_green": 5,
    "light_lime": 15,
    "light_nougat": 33,
    "light_orange": 2,
    "light_pink": 1,
    "light_salmon": 1,
    "light_yellow": 14,
    "lilac": 1,
    "lime": 9,
    "maersk_blue": 4,
    "magenta": 5,
    "medium_azure": 17,
    "medium_blue": 170,
    "medium_brown": 10,
    "medium_dark_pink": 2,
    "medium_green": 4,
    "medium_lavender": 106,
    "medium_lime": 2,
    "medium_nougat": 40,
    "medium_orange": 12,
    "medium_tan": 6,
    "neon_green": 2,
    "neon_orange": 48,
    "neon_yellow": 128,
    "nougat": 43,
    "olive_green": 18,
    "orange": 879,
    "pink": 11,
    "purple": 6,
    "red": 4453,
    "reddish_brown": 1798,
    "rust": 25,
    "salmon": 2,
    "sand_blue": 17,
    "sand_green": 65,
    "sand_purple": 1,
    "sky_blue": 4,
    "tan": 7749,
    "very_light_bluish_gray": 42,
    "very_light_gray": 24,
    "very_light_orange": 9,
    "violet": 4,
    "white": 20930,
    "yellow": 5984,
    "yellowish_green": 2,
    "trans_aqua": 2,
    "trans_black": 6,
    "trans_brown": 18,
    "trans_clear": 49,
    "trans_dark_blue": 7,
    "trans_light_blue": 10,
    "trans_medium_blue": 1,
    "trans_neon_orange": 1,
    "trans_red": 2,
    "trans_yellow": 1,
    "chrome_antique_brass": 1,
    "chrome_gold": 1,
    "chrome_green": 1,
    "chrome_silver": 9,
    "copper": 1,
    "flat_silver": 98,
    "pearl_black": 4,
    "pearl_dark_gray": 11,
    "pearl_gold": 11,
    "pearl_light_gray": 11,
    "pearl_very_light_gray": 1,
    "pearl_white": 2,
    "metallic_copper": 1,
    "metallic_silver": 17,
    "glow_in_dark_white": 8,
    "glitter_trans_clear": 1
}

piece_3245c = {
    "Aqua": 5,
    "Black": 48785,
    "Blue": 3792,
    "Blue-Violet": 8,
    "Bright Green": 2409,
    "Bright Light Blue": 10,
    "Bright Light Orange": 663,
    "Bright Light Yellow": 9,
    "Bright Pink": 66,
    "Brown": 76,
    "Clikits Lavender": 1,
    "Dark Azure": 732,
    "Dark Blue": 163,
    "Dark Blue-Violet": 8,
    "Dark Bluish Gray": 46065,
    "Dark Brown": 50,
    "Dark Gray": 101,
    "Dark Green": 136,
    "Dark Nougat": 5,
    "Dark Orange": 17,
    "Dark Pink": 14,
    "Dark Purple": 20,
    "Dark Red": 3723,
    "Dark Tan": 108,
    "Dark Turquoise": 166,
    "Dark Yellow": 1,
    "Earth Orange": 7,
    "Fabuland Brown": 10,
    "Fabuland Orange": 9,
    "Green": 1704,
    "Lavender": 11,
    "Light Aqua": 6,
    "Light Blue": 3,
    "Light Bluish Gray": 70222,
    "Light Brown": 14,
    "Light Gray": 362,
    "Light Green": 1,
    "Light Nougat": 20,
    "Light Pink": 2,
    "Light Purple": 2,
    "Light Salmon": 2,
    "Light Turquoise": 1,
    "Light Yellow": 18,
    "Lime": 359,
    "Maersk Blue": 2,
    "Magenta": 55,
    "Medium Azure": 12,
    "Medium Blue": 462,
    "Medium Brown": 6,
    "Medium Dark Pink": 1,
    "Medium Green": 5,
    "Medium Lavender": 416,
    "Medium Lime": 3,
    "Medium Nougat": 342,
    "Medium Orange": 3,
    "Medium Tan": 3,
    "Medium Violet": 1,
    "Nougat": 45,
    "Olive Green": 29,
    "Orange": 2797,
    "Pink": 4,
    "Purple": 3,
    "Red": 16986,
    "Reddish Brown": 15077,
    "Rust": 18,
    "Salmon": 3,
    "Sand Blue": 81,
    "Sand Green": 4554,
    "Sand Red": 2,
    "Sky Blue": 4,
    "Tan": 36394,
    "Very Light Bluish Gray": 56,
    "Very Light Gray": 10,
    "Very Light Orange": 1,
    "Violet": 2,
    "White": 53693,
    "Yellow": 8564,
    "Trans-Aqua": 2,
    "Trans-Black (2023)": 1,
    "Trans-Brown (Old Trans-Black)": 49,
    "Trans-Clear": 48,
    "Trans-Dark Blue": 2,
    "Trans-Light Blue": 53,
    "Trans-Medium Blue": 7,
    "Trans-Neon Green": 1,
    "Trans-Orange": 1,
    "Trans-Red": 2,
    "Trans-Yellow": 1,
    "Chrome Black": 1,
    "Chrome Gold": 1,
    "Chrome Silver": 9,
    "Copper": 2,
    "Flat Silver": 19,
    "Pearl Black": 1,
    "Pearl Dark Gray": 24,
    "Pearl Gold": 7,
    "Pearl Light Gray": 1,
    "Pearl Sand Blue": 1,
    "Pearl White": 2,
    "Metallic Gold": 2,
    "Metallic Silver": 9,
    "Glow In Dark White": 2,
    "Milky White": 1,
}

piece_2453a = {
    "aqua": 5,
    "black": 9623,
    "blue": 717,
    "blue_violet": 3,
    "bright_green": 10,
    "bright_light_blue": 5,
    "bright_light_orange": 10,
    "bright_light_yellow": 35,
    "brown": 808,
    "clikits_lavender": 2,
    "dark_azure": 1,
    "dark_blue": 22,
    "dark_blue_violet": 2,
    "dark_bluish_gray": 7129,
    "dark_brown": 66,
    "dark_gray": 518,
    "dark_green": 535,
    "dark_nougat": 5,
    "dark_orange": 420,
    "dark_pink": 107,
    "dark_purple": 21,
    "dark_red": 2152,
    "dark_tan": 81,
    "dark_turquoise": 19,
    "dark_yellow": 3,
    "earth_orange": 1,
    "fabuland_brown": 18,
    "fabuland_orange": 2,
    "green": 38,
    "lavender": 6,
    "light_aqua": 2,
    "light_blue": 1,
    "light_bluish_gray": 8860,
    "light_brown": 46,
    "light_gray": 4574,
    "light_lime": 1,
    "light_nougat": 7,
    "light_orange": 3,
    "light_pink": 1,
    "light_purple": 2,
    "light_salmon": 1,
    "light_turquoise": 2,
    "light_yellow": 165,
    "lime": 5,
    "maersk_blue": 6,
    "magenta": 18,
    "medium_azure": 8,
    "medium_blue": 12,
    "medium_brown": 4,
    "medium_green": 3,
    "medium_lavender": 2,
    "medium_lime": 1,
    "medium_nougat": 125,
    "medium_orange": 4,
    "medium_tan": 6,
    "neon_green": 1,
    "nougat": 14,
    "olive_green": 4,
    "orange": 313,
    "pink": 1,
    "purple": 1,
    "red": 3068,
    "reddish_brown": 4844,
    "rust": 11,
    "sand_blue": 17,
    "sand_green": 70,
    "sky_blue": 6,
    "tan": 5556,
    "very_light_bluish_gray": 29,
    "very_light_gray": 28,
    "very_light_orange": 7,
    "violet": 4,
    "white": 12584,
    "yellow": 2109,
    "trans_brown": 10,
    "trans_clear": 109,
    "trans_dark_blue": 3,
    "trans_dark_pink": 2,
    "trans_light_blue": 16,
    "trans_medium_blue": 16,
    "trans_neon_orange": 1,
    "trans_orange": 1,
    "trans_yellow": 1,
    "chrome_black": 2,
    "chrome_gold": 3,
    "chrome_silver": 3,
    "copper": 4,
    "flat_dark_gold": 1,
    "flat_silver": 30,
    "pearl_black": 2,
    "pearl_dark_gray": 7,
    "pearl_gold": 10,
    "pearl_light_gold": 1,
    "pearl_light_gray": 3,
    "pearl_white": 1,
    "metallic_gold": 1,
    "metallic_silver": 10,
    "glow_in_dark_white": 4,
}

piece_2453b = {
    "aqua": 4,
    "black": 16164,
    "blue": 566,
    "blue_violet": 5,
    "bright_green": 12,
    "bright_light_blue": 12,
    "bright_light_orange": 1005,
    "bright_light_yellow": 1559,
    "bright_pink": 564,
    "brown": 256,
    "clikits_lavender": 2,
    "dark_azure": 7,
    "dark_blue": 33,
    "dark_blue_violet": 7,
    "dark_bluish_gray": 18064,
    "dark_brown": 295,
    "dark_gray": 129,
    "dark_green": 59,
    "dark_nougat": 6,
    "dark_orange": 63,
    "dark_pink": 4,
    "dark_purple": 319,
    "dark_red": 2592,
    "dark_salmon": 1,
    "dark_tan": 124,
    "dark_turquoise": 305,
    "dark_yellow": 1,
    "earth_orange": 4,
    "fabuland_brown": 63,
    "fabuland_lime": 2,
    "fabuland_orange": 4,
    "green": 85,
    "lavender": 107,
    "light_aqua": 600,
    "light_blue": 5,
    "light_bluish_gray": 32322,
    "light_brown": 40,
    "light_gray": 340,
    "light_green": 1,
    "light_lime": 1,
    "light_nougat": 48,
    "light_orange": 4,
    "light_pink": 1,
    "light_purple": 2,
    "light_turquoise": 4,
    "light_yellow": 21,
    "lime": 48,
    "maersk_blue": 1,
    "magenta": 127,
    "medium_azure": 305,
    "medium_blue": 14,
    "medium_brown": 6,
    "medium_green": 4,
    "medium_lavender": 1,
    "medium_lime": 2,
    "medium_nougat": 3376,
    "medium_orange": 2,
    "medium_tan": 12,
    "neon_green": 1,
    "neon_orange": 4,
    "neon_yellow": 2,
    "nougat": 24,
    "olive_green": 3,
    "orange": 133,
    "pink": 2,
    "purple": 8,
    "red": 5098,
    "reddish_brown": 27722,
    "rust": 21,
    "salmon": 1,
    "sand_blue": 68,
    "sand_green": 1898,
    "sand_red": 1,
    "sky_blue": 7,
    "tan": 26492,
    "very_light_bluish_gray": 14,
    "very_light_gray": 37,
    "very_light_orange": 4,
    "violet": 1,
    "white": 37376,
    "yellow": 3075,
    "yellowish_green": 76,
    "trans_aqua": 1,
    "trans_black": 2,
    "trans_bright_green": 1,
    "trans_brown": 19,
    "trans_clear": 86,
    "trans_dark_blue": 4,
    "trans_light_blue": 19,
    "trans_light_purple": 1,
    "trans_medium_blue": 35,
    "trans_neon_orange": 2,
    "trans_neon_yellow": 3,
    "trans_orange": 1,
    "trans_red": 1,
    "trans_yellow": 16,
    "chrome_antique_brass": 1,
    "chrome_black": 1,
    "chrome_gold": 4,
    "chrome_silver": 4,
    "copper": 3,
    "flat_silver": 48,
    "pearl_black": 7,
    "pearl_dark_gray": 6,
    "pearl_gold": 82,
    "pearl_light_gray": 3,
    "pearl_white": 2,
    "satin_trans_clear": 1,
    "metallic_copper": 2,
    "metallic_gold": 4,
    "metallic_green": 1,
    "metallic_silver": 4,
    "glow_in_dark_white": 7,
}

piece_3001 = {
    "aqua": 10,
    "black": 10,
    "blue": 10,
    "blue_violet": 10,
    "bright_green": 10,
    "bright_light_blue": 10,
    "bright_light_orange": 10,
    "bright_light_yellow": 10,
    "bright_pink": 10,
    "brown": 10,
    "clikits_lavender": 10,
    "coral": 10,
    "dark_azure": 10,
    "dark_blue": 10,
    "dark_blue_violet": 10,
    "dark_bluish_gray": 10,
    "dark_brown": 10,
    "dark_gray": 10,
    "dark_green": 10,
    "dark_nougat": 10,
    "dark_olive_green": 10,
    "dark_orange": 10,
    "dark_pink": 10,
    "dark_purple": 10,
    "dark_red": 10,
    "dark_salmon": 10,
    "dark_tan": 10,
    "dark_turquoise": 10,
    "dark_yellow": 10,
    "earth_orange": 10,
    "fabuland_brown": 10,
    "fabuland_lime": 10,
    "fabuland_orange": 10,
    "green": 10,
    "lavender": 10,
    "light_aqua": 10,
    "light_blue": 10,
    "light_bluish_gray": 10,
    "light_brown": 10,
    "light_gray": 10,
    "light_green": 10,
    "light_lilac": 10,
    "light_lime": 10,
    "light_nougat": 10,
    "light_orange": 10,
    "light_pink": 10,
    "light_purple": 10,
    "light_salmon": 10,
    "light_turquoise": 10,
    "light_violet": 10,
    "light_yellow": 10,
    "lilac": 10,
    "lime": 10,
    "little_robots_blue": 10,
    "maersk_blue": 10,
    "magenta": 10,
    "medium_azure": 10,
    "medium_blue": 10,
    "medium_brown": 10,
    "medium_dark_pink": 10,
    "medium_green": 10,
    "medium_lavender": 10,
    "medium_lime": 10,
    "medium_nougat": 10,
    "medium_orange": 10,
    "medium_tan": 10,
    "medium_violet": 10,
    "neon_green": 10,
    "neon_orange": 10,
    "neon_yellow": 10,
    "nougat": 10,
    "olive_green": 10,
    "orange": 10,
    "pink": 10,
    "purple": 10,
    "red": 10,
    "reddish_brown": 10,
    "rust": 10,
    "salmon": 10,
    "sand_blue": 10,
    "sand_green": 10,
    "sand_purple": 10,
    "sand_red": 10,
    "sky_blue": 10,
    "tan": 10,
    "very_light_bluish_gray": 10,
    "very_light_gray": 10,
    "very_light_orange": 10,
    "violet": 10,
    "white": 10,
    "yellow": 10,
    "yellowish_green": 10,
    "trans_aqua": 10,
    "trans_black": 10,
    "trans_bright_green": 10,
    "trans_brown": 10,
    "trans_clear": 10,
    "trans_dark_blue": 10,
    "trans_dark_pink": 10,
    "trans_green": 10,
    "trans_light_blue": 10,
    "trans_light_bright_green": 10,
    "trans_light_green": 10,
    "trans_light_orange": 10,
    "trans_light_purple": 10,
    "trans_medium_blue": 10,
    "trans_medium_purple": 10,
    "trans_neon_green": 10,
    "trans_neon_orange": 10,
    "trans_neon_yellow": 10,
    "trans_orange": 10,
    "trans_pink": 10,
    "trans_purple": 10,
    "trans_red": 10,
    "trans_yellow": 10,
    "chrome_antique_brass": 10,
    "chrome_black": 10,
    "chrome_blue": 10,
    "chrome_gold": 10,
    "chrome_green": 10,
    "chrome_pink": 10,
    "chrome_silver": 10,
    "bionicle_copper": 10,
    "bionicle_gold": 10,
    "bionicle_silver": 10,
    "copper": 10,
    "flat_dark_gold": 10,
    "flat_silver": 10,
    "pearl_black": 10,
    "pearl_blue": 10,
    "pearl_brown": 10,
    "pearl_dark_gray": 10,
    "pearl_gold": 10,
    "pearl_green": 10,
    "pearl_light_gold": 10,
    "pearl_light_gray": 10,
    "pearl_red": 10,
    "pearl_sand_blue": 10,
    "pearl_sand_purple": 10,
    "pearl_very_light_gray": 10,
    "pearl_white": 10,
    "reddish_copper": 10,
    "reddish_gold": 10,
    "satin_trans_bright_green": 10,
    "satin_trans_brown": 10,
    "satin_trans_clear": 10,
    "satin_trans_dark_blue": 10,
    "satin_trans_dark_pink": 10,
    "satin_trans_light_blue": 10,
    "satin_trans_purple": 10,
    "metallic_copper": 10,
    "metallic_gold": 10,
    "metallic_green": 10,
    "metallic_silver": 10,
    "glow_in_dark_opaque": 10,
    "glow_in_dark_trans": 10,
    "glow_in_dark_white": 10,
    "milky_white": 10,
    "glitter_trans_clear": 10,
    "glitter_trans_dark_pink": 10,
    "glitter_trans_light_blue": 10,
    "glitter_trans_neon_green": 10,
    "glitter_trans_orange": 10,
    "glitter_trans_purple": 10,
}

piece_3004 = {
    "Aqua": 363,
    "Black": 434623,
    "Blue": 98063,
    "Blue-Violet": 617,
    "Bright Green": 6075,
    "Bright Light Blue": 9528,
    "Bright Light Orange": 17693,
    "Bright Light Yellow": 9646,
    "Bright Pink": 13486,
    "Brown": 18208,
    "Clikits Lavender": 60,
    "Coral": 2389,
    "Dark Azure": 12518,
    "Dark Blue": 55611,
    "Dark Blue-Violet": 141,
    "Dark Bluish Gray": 316305,
    "Dark Brown": 17039,
    "Dark Gray": 14675,
    "Dark Green": 52767,
    "Dark Nougat": 244,
    "Dark Olive Green": 8,
    "Dark Orange": 28482,
    "Dark Pink": 6476,
    "Dark Purple": 10613,
    "Dark Red": 94773,
    "Dark Salmon": 9,
    "Dark Tan": 85960,
    "Dark Turquoise": 7473,
    "Dark Yellow": 91,
    "Earth Orange": 283,
    "Fabuland Brown": 396,
    "Fabuland Lime": 11,
    "Fabuland Orange": 39,
    "Green": 47799,
    "Lavender": 4274,
    "Light Aqua": 5466,
    "Light Blue": 254,
    "Light Bluish Gray": 428335,
    "Light Brown": 689,
    "Light Gray": 45459,
    "Light Green": 217,
    "Light Lilac": 1,
    "Light Lime": 170,
    "Light Nougat": 2098,
    "Light Orange": 218,
    "Light Pink": 189,
    "Light Purple": 392,
    "Light Salmon": 109,
    "Light Turquoise": 169,
    "Light Violet": 92,
    "Light Yellow": 1044,
    "Lilac": 22,
    "Lime": 28359,
    "Little Robots Blue": 3,
    "Maersk Blue": 1480,
    "Magenta": 5121,
    "Medium Azure": 11999,
    "Medium Blue": 32338,
    "Medium Brown": 120,
    "Medium Dark Pink": 196,
    "Medium Green": 553,
    "Medium Lavender": 6494,
    "Medium Lime": 124,
    "Medium Nougat": 39299,
    "Medium Orange": 224,
    "Medium Tan": 83,
    "Medium Violet": 162,
    "Neon Green": 86,
    "Neon Orange": 43,
    "Neon Yellow": 320,
    "Nougat": 1504,
    "Olive Green": 17194,
    "Orange": 38084,
    "Pink": 1094,
    "Purple": 1139,
    "Red": 171229,
    "Reddish Brown": 157202,
    "Rust": 233,
    "Salmon": 62,
    "Sand Blue": 10893,
    "Sand Green": 30272,
    "Sand Purple": 116,
    "Sand Red": 741,
    "Sky Blue": 247,
    "Tan": 212460,
    "Very Light Bluish Gray": 1682,
    "Very Light Gray": 385,
    "Very Light Orange": 131,
    "Violet": 99,
    "White": 371791,
    "Yellow": 100035,
    "Yellowish Green": 2901,
    "Trans-Aqua": 166,
    "Trans-Black": 2023,
    "Trans-Bright Green": 177,
    "Trans-Brown (Old Trans-Black)": 1424,
    "Trans-Clear": 23577,
    "Trans-Dark Blue": 615,
    "Trans-Dark Pink": 173,
    "Trans-Green": 253,
    "Trans-Light Blue": 843,
    "Trans-Light Bright Green": 72,
    "Trans-Light Green": 65,
    "Trans-Light Orange": 68,
    "Trans-Light Purple": 38,
    "Trans-Medium Blue": 257,
    "Trans-Medium Purple": 22,
    "Trans-Neon Green": 181,
    "Trans-Neon Orange": 193,
    "Trans-Neon Yellow": 144,
    "Trans-Orange": 152,
    "Trans-Pink": 143,
    "Trans-Purple": 180,
    "Trans-Red": 949,
    "Trans-Yellow": 482,
    "Chrome Antique Brass": 14,
    "Chrome Black": 39,
    "Chrome Blue": 20,
    "Chrome Gold": 177,
    "Chrome Green": 15,
    "Chrome Pink": 13,
    "Chrome Silver": 476,
    "Bionicle Copper": 4,
    "Bionicle Gold": 4,
    "Bionicle Silver": 4,
    "Copper": 79,
    "Flat Dark Gold": 64,
    "Flat Silver": 474,
    "Pearl Black": 29,
    "Pearl Dark Gray": 413,
    "Pearl Gold": 193,
    "Pearl Light Gold": 56,
    "Pearl Light Gray": 288,
    "Pearl Sand Blue": 52,
    "Pearl Very Light Gray": 36,
    "Pearl White": 27,
    "Reddish Gold": 10,
    "Satin Trans-Bright Green": 10,
    "Satin Trans-Brown": 15,
    "Satin Trans-Clear": 32,
    "Satin Trans-Dark Blue": 26,
    "Satin Trans-Dark Pink": 8,
    "Satin Trans-Light Blue": 11,
    "Satin Trans-Purple": 5,
    "Metallic Copper": 1,
    "Metallic Gold": 106,
    "Metallic Green": 34,
    "Metallic Silver": 260,
    "Glow In Dark Opaque": 55,
    "Glow In Dark Trans": 18,
    "Glow In Dark White": 116,
    "Milky White": 55,
    "Glitter Trans-Clear": 13,
    "Glitter Trans-Dark Pink": 91,
    "Glitter Trans-Light Blue": 48,
    "Glitter Trans-Neon Green": 28,
    "Glitter Trans-Orange": 6,
    "Glitter Trans-Purple": 35,
}

piece_3005 = {
    "aqua": 511,
    "black": 367667,
    "blue": 74319,
    "blue_violet": 132,
    "bright_green": 1894,
    "bright_light_blue": 4068,
    "bright_light_orange": 15019,
    "bright_light_yellow": 5991,
    "bright_pink": 9843,
    "brown": 13340,
    "clikits_lavender": 43,
    "coral": 1481,
    "dark_azure": 8170,
    "dark_blue": 51120,
    "dark_blue_violet": 131,
    "dark_bluish_gray": 283596,
    "dark_brown": 12186,
    "dark_gray": 9945,
    "dark_green": 48054,
    "dark_nougat": 233,
    "dark_olive_green": 9,
    "dark_orange": 29396,
    "dark_pink": 6909,
    "dark_purple": 8934,
    "dark_red": 81461,
    "dark_salmon": 10,
    "dark_tan": 69761,
    "dark_turquoise": 7111,
    "dark_yellow": 60,
    "earth_orange": 201,
    "fabuland_brown": 435,
    "fabuland_lime": 13,
    "fabuland_orange": 46,
    "green": 36820,
    "lavender": 4709,
    "light_aqua": 2753,
    "light_blue": 189,
    "light_bluish_gray": 393736,
    "light_brown": 679,
    "light_gray": 37599,
    "light_green": 129,
    "light_lilac": 4,
    "light_lime": 37,
    "light_nougat": 2428,
    "light_orange": 195,
    "light_pink": 139,
    "light_purple": 147,
    "light_salmon": 69,
    "light_turquoise": 89,
    "light_violet": 98,
    "light_yellow": 580,
    "lilac": 26,
    "lime": 23066,
    "little_robots_blue": 4,
    "maersk_blue": 1553,
    "magenta": 5406,
    "medium_azure": 12131,
    "medium_blue": 30936,
    "medium_brown": 141,
    "medium_dark_pink": 106,
    "medium_green": 500,
    "medium_lavender": 5271,
    "medium_lime": 93,
    "medium_nougat": 57192,
    "medium_orange": 840,
    "medium_tan": 89,
    "medium_violet": 56,
    "neon_green": 41,
    "neon_orange": 48,
    "neon_yellow": 128,
    "nougat": 1453,
    "olive_green": 18343,
    "orange": 31475,
    "pink": 1316,
    "purple": 391,
    "red": 140657,
    "reddish_brown": 157059,
    "rust": 228,
    "salmon": 62,
    "sand_blue": 19700,
    "sand_green": 39802,
    "sand_purple": 49,
    "sand_red": 59,
    "sky_blue": 110,
    "tan": 186337,
    "very_light_bluish_gray": 721,
    "very_light_gray": 385,
    "very_light_orange": 102,
    "violet": 71,
    "white": 332619,
    "yellow": 78337,
    "yellowish_green": 1339,
    "trans_aqua": 180,
    "trans_black": 2023,
    "trans_bright_green": 235,
    "trans_brown": 21538,
    "trans_clear": 70234,
    "trans_dark_blue": 9080,
    "trans_dark_pink": 3389,
    "trans_green": 2493,
    "trans_light_blue": 12490,
    "trans_light_bright_green": 33,
    "trans_light_green": 17,
    "trans_light_orange": 159,
    "trans_light_purple": 72,
    "trans_medium_blue": 1166,
    "trans_medium_purple": 11,
    "trans_neon_green": 134,
    "trans_neon_orange": 960,
    "trans_neon_yellow": 83,
    "trans_orange": 16360,
    "trans_pink": 121,
    "trans_purple": 4838,
    "trans_red": 5419,
    "trans_yellow": 4531,
    "chrome_antique_brass": 21,
    "chrome_black": 39,
    "chrome_blue": 20,
    "chrome_gold": 159,
    "chrome_green": 14,
    "chrome_pink": 12,
    "chrome_silver": 447,
    "bionicle_copper": 6,
    "bionicle_gold": 7,
    "bionicle_silver": 9,
    "copper": 90,
    "flat_dark_gold": 106,
    "flat_silver": 531,
    "pearl_black": 29,
    "pearl_dark_gray": 553,
    "pearl_gold": 244,
    "pearl_light_gold": 61,
    "pearl_light_gray": 311,
    "pearl_sand_blue": 26,
    "pearl_sand_purple": 3,
    "pearl_very_light_gray": 27,
    "pearl_white": 41,
    "reddish_copper": 2,
    "reddish_gold": 10,
    "satin_trans_bright_green": 14,
    "satin_trans_brown": 13,
    "satin_trans_clear": 31,
    "satin_trans_dark_blue": 30,
    "satin_trans_dark_pink": 10,
    "satin_trans_light_blue": 31,
    "satin_trans_purple": 7,
    "metallic_copper": 2,
    "metallic_gold": 103,
    "metallic_green": 33,
    "metallic_silver": 332,
    "glow_in_dark_opaque": 79,
    "glow_in_dark_trans": 20,
    "glow_in_dark_white": 177,
    "milky_white": 67,
    "glitter_trans_clear": 14,
    "glitter_trans_dark_pink": 1933,
    "glitter_trans_light_blue": 10,
    "glitter_trans_neon_green": 33,
    "glitter_trans_orange": 10,
    "glitter_trans_purple": 1432, 
}

piece_3065 = {
    "aqua": 56,
    "black": 7332,
    "blue": 1175,
    "blue_violet": 45,
    "bright_green": 114,
    "bright_light_blue": 92,
    "bright_light_orange": 87,
    "bright_light_yellow": 95,
    "bright_pink": 62,
    "brown": 348,
    "clikits_lavender": 12,
    "coral": 45,
    "dark_azure": 78,
    "dark_blue": 307,
    "dark_blue_violet": 32,
    "dark_bluish_gray": 2555,
    "dark_brown": 220,
    "dark_gray": 362,
    "dark_green": 236,
    "dark_nougat": 34,
    "dark_olive_green": 0,  # No quantity provided
    "dark_orange": 148,
    "dark_pink": 63,
    "dark_purple": 62,
    "dark_red": 300,
    "dark_salmon": 3,
    "dark_tan": 362,
    "dark_turquoise": 61,
    "dark_yellow": 9,
    "earth_orange": 45,
    "fabuland_brown": 77,
    "fabuland_lime": 3,
    "fabuland_orange": 6,
    "green": 250,
    "lavender": 42,
    "light_aqua": 42,
    "light_blue": 43,
    "light_bluish_gray": 1888,
    "light_brown": 119,
    "light_gray": 701,
    "light_green": 30,
    "light_lime": 9,
    "light_nougat": 139,
    "light_orange": 41,
    "light_pink": 48,
    "light_purple": 30,
    "light_salmon": 28,
    "light_turquoise": 36,
    "light_violet": 38,
    "light_yellow": 137,
    "lilac": 2,
    "lime": 82,
    "maersk_blue": 32,
    "magenta": 51,
    "medium_azure": 62,
    "medium_blue": 104,
    "medium_brown": 47,
    "medium_dark_pink": 27,
    "medium_green": 44,
    "medium_lavender": 50,
    "medium_lime": 50,
    "medium_nougat": 106,
    "medium_orange": 77,
    "medium_tan": 33,
    "medium_violet": 20,
    "neon_green": 5,
    "neon_orange": 3,
    "neon_yellow": 10,
    "nougat": 119,
    "olive_green": 0,  # No quantity provided
    "orange": 148,
    "pink": 50,
    "purple": 52,
    "red": 2701,
    "reddish_brown": 401,
    "rust": 68,
    "salmon": 27,
    "sand_blue": 124,
    "sand_green": 131,
    "sand_purple": 10,
    "sand_red": 5,
    "sky_blue": 19,
    "tan": 1213,
    "very_light_bluish_gray": 181,
    "very_light_gray": 100,
    "very_light_orange": 12,
    "violet": 42,
    "white": 9102,
    "yellow": 1263,
    "yellowish_green": 44,
    "trans_aqua": 34,
    "trans_black": 2023,
    "trans_bright_green": 3208,
    "trans_brown": 33744,
    "trans_clear": 72268,
    "trans_dark_blue": 7673,
    "trans_dark_pink": 3642,
    "trans_green": 7415,
    "trans_light_blue": 11691,
    "trans_light_bright_green": 51,
    "trans_light_green": 12,
    "trans_light_orange": 51,
    "trans_light_purple": 22,
    "trans_medium_blue": 760,
    "trans_medium_purple": 8,
    "trans_neon_green": 1047,
    "trans_neon_orange": 1326,
    "trans_neon_yellow": 95,
    "trans_orange": 210,
    "trans_pink": 78,
    "trans_purple": 1949,
    "trans_red": 12901,
    "trans_yellow": 8056,
    "chrome_antique_brass": 5,
    "chrome_black": 14,
    "chrome_blue": 3,
    "chrome_gold": 81,
    "chrome_green": 4,
    "chrome_pink": 3,
    "chrome_silver": 75,
    "bionicle_copper": 3,
    "bionicle_gold": 3,
    "bionicle_silver": 3,
    "copper": 63,
    "flat_dark_gold": 48,
    "flat_silver": 99,
    "pearl_black": 5,
    "pearl_dark_gray": 110,
    "pearl_gold": 75,
    "pearl_light_gold": 44,
    "pearl_light_gray": 82,
    "pearl_sand_blue": 9,
    "pearl_sand_purple": 8,  # Updated from 3 to 8
    "pearl_very_light_gray": 27,
    "pearl_white": 6,
    "reddish_copper": 0,  # No quantity provided
    "reddish_gold": 7,
    "satin_trans_bright_green": 7,
    "satin_trans_brown": 10,
    "satin_trans_clear": 26,
    "satin_trans_dark_blue": 25,
    "satin_trans_dark_pink": 6,
    "satin_trans_light_blue": 515,
    "satin_trans_purple": 3,
    "metallic_copper": 0,  # No quantity provided
    "metallic_gold": 68,
    "metallic_green": 10,
    "metallic_silver": 84,
    "glow_in_dark_opaque": 44,
    "glow_in_dark_trans": 7,
    "glow_in_dark_white": 88,
    "milky_white": 38,
    "glitter_trans_clear": 8,
    "glitter_trans_dark_pink": 279,
    "glitter_trans_light_blue": 569,
    "glitter_trans_neon_green": 24,
    "glitter_trans_orange": 5,
    "glitter_trans_purple": 10,

}

piece_14716 = {
    "aqua": 19,
    "black": 28176,
    "blue": 201,
    "blue_violet": 5,
    "bright_green": 38,
    "bright_light_blue": 45,
    "bright_light_orange": 998,
    "bright_light_yellow": 896,
    "bright_pink": 328,
    "brown": 365,
    "clikits_lavender": 3,
    "coral": 4,
    "dark_azure": 282,
    "dark_blue": 1598,
    "dark_blue_violet": 11,
    "dark_bluish_gray": 1394,
    "dark_brown": 2891,
    "dark_gray": 206,
    "dark_green": 130,
    "dark_nougat": 11,
    "dark_orange": 381,
    "dark_pink": 5,
    "dark_purple": 324,
    "dark_red": 158,
    "dark_tan": 2136,
    "dark_turquoise": 122,
    "dark_yellow": 2,
    "earth_orange": 12,
    "fabuland_brown": 47,
    "fabuland_lime": 1,
    "fabuland_orange": 7,
    "green": 139,
    "lavender": 9,
    "light_aqua": 9,
    "light_blue": 16,
    "light_bluish_gray": 53449,
    "light_brown": 73,
    "light_gray": 615,
    "light_green": 1,
    "light_lime": 4,
    "light_nougat": 58,
    "light_orange": 7,
    "light_pink": 4,
    "light_purple": 2,
    "light_salmon": 2,
    "light_turquoise": 14,
    "light_yellow": 111,
    "lilac": 1,
    "lime": 406,
    "maersk_blue": 14,
    "magenta": 3,
    "medium_azure": 3199,
    "medium_blue": 374,
    "medium_brown": 14,
    "medium_dark_pink": 3,
    "medium_green": 5,
    "medium_lavender": 22,
    "medium_lime": 6,
    "medium_nougat": 953,
    "medium_orange": 4,
    "medium_tan": 15,
    "medium_violet": 1,
    "neon_green": 1,
    "neon_orange": 3,
    "neon_yellow": 128,
    "nougat": 49,
    "olive_green": 103,
    "orange": 59,
    "pink": 5,
    "purple": 15,
    "red": 11273,
    "reddish_brown": 17391,
    "rust": 40,
    "salmon": 62,
    "sand_blue": 94,
    "sand_green": 943,
    "sand_purple": 2,
    "sand_red": 3,
    "sky_blue": 11,
    "tan": 24869,
    "very_light_bluish_gray": 103,
    "very_light_gray": 98,
    "very_light_orange": 3,
    "violet": 4,
    "white": 35426,
    "yellow": 239,
    "yellowish_green": 7,
    "trans_aqua": 25,
    "trans_black": 1,
    "trans_brown": 41,
    "trans_clear": 72,
    "trans_dark_blue": 5,
    "trans_light_blue": 23,
    "trans_light_orange": 1,
    "trans_light_purple": 1,
    "trans_medium_blue": 22,
    "trans_neon_green": 1,
    "trans_neon_orange": 2,
    "trans_neon_yellow": 1,
    "trans_orange": 2,
    "trans_purple": 1,
    "trans_yellow": 2,
    "chrome_antique_brass": 4,
    "chrome_black": 7,
    "chrome_blue": 1,
    "chrome_gold": 11,
    "chrome_pink": 2,
    "chrome_silver": 36,
    "bionicle_gold": 2,
    "copper": 2,
    "flat_silver": 132,
    "pearl_black": 6,
    "pearl_dark_gray": 38,
    "pearl_gold": 13,
    "pearl_light_gray": 5,
    "pearl_very_light_gray": 2,
    "pearl_white": 2,
    "metallic_copper": 1,
    "metallic_gold": 5,
    "metallic_silver": 14,
    "glow_in_dark_white": 13,
    "milky_white": 1,
    "glitter_trans_purple": 2,
    "mx_violet": 1
}

selected_piece = input("Enter the piece number: ")
selected_color = input("Enter the color: ")

if selected_piece == "3001":
    total = piece_3001.get(selected_color, 0)
elif selected_piece == "2039":
    total = piece_2039.get(selected_color, 0)
elif selected_piece == "2038":
    total = piece_2038.get(selected_color, 0)
elif selected_piece == "2335":
    total = piece_2335.get(selected_color, 0)
elif selected_piece == "3005":
    total = piece_3005.get(selected_color, 0)
elif selected_piece == "2336":
    total = piece_2336.get(selected_color, 0)
elif selected_piece == "2338":
    total = piece_2338.get(selected_color, 0)
elif selected_piece == "2339":
    total = piece_2339.get(selected_color, 0)
elif selected_piece == "2340":
    total = piece_2340.get(selected_color, 0)
elif selected_piece == "2341":
    total = piece_2341.get(selected_color, 0)
elif selected_piece == "2342":
    total = piece_2342.get(selected_color, 0)


else:
    print(f"Piece {selected_piece} not found in inventory")

print(f"Total quantity of {selected_color} {selected_piece}: {total}")

