import tkinter as tk
from tkinter import ttk

piece_772 = {
    "aqua": 6,
    "black": 289,
    "blue": 46,
    "blue_violet": 4,
    "bright_green": 6,
    "bright_light_blue": 4,
    "bright_light_orange": 3,
    "bright_light_yellow": 8,
    "bright_pink": 2,
    "brown": 57,
    "dark_azure": 4,
    "dark_blue": 19,
    "dark_blue_violet": 6,
    "dark_bluish_gray": 1033,
    "dark_brown": 17,
    "dark_gray": 64,
    "dark_green": 24,
    "dark_nougat": 7,
    "dark_orange": 8,
    "dark_pink": 2,
    "dark_purple": 2,
    "dark_red": 56,
    "dark_tan": 18,
    "dark_turquoise": 3,
    "earth_orange": 4,
    "fabuland_brown": 8,
    "fabuland_orange": 1,
    "green": 8,
    "light_blue": 1,
    "light_bluish_gray": 830,
    "light_brown": 19,
    "light_gray": 142,
    "light_green": 2,
    "light_nougat": 3,
    "light_pink": 2,
    "light_salmon": 2,
    "light_turquoise": 1,
    "light_violet": 2,
    "light_yellow": 15,
    "lime": 1,
    "maersk_blue": 3,
    "magenta": 2,
    "medium_azure": 1,
    "medium_blue": 19,
    "medium_brown": 3,
    "medium_dark_pink": 1,
    "medium_lavender": 1,
    "medium_lime": 1,
    "medium_nougat": 13,
    "medium_orange": 1,
    "medium_tan": 6,
    "neon_green": 1,
    "nougat": 16,
    "olive_green": 7,
    "orange": 5,
    "pink": 3,
    "purple": 2,
    "red": 307,
    "reddish_brown": 33,
    "rust": 11,
    "salmon": 1,
    "sand_blue": 7,
    "sand_green": 4,
    "sand_purple": 3,
    "sky_blue": 1,
    "tan": 1028,
    "very_light_bluish_gray": 10,
    "very_light_gray": 22,
    "very_light_orange": 1,
    "white": 1803,
    "yellow": 27,
    "yellowish_green": 3,
    "trans_brown": 18,
    "trans_clear": 180,
    "trans_dark_blue": 3,
    "trans_light_blue": 11,
    "trans_medium_blue": 5,
    "trans_neon_green": 1,
    "trans_neon_orange": 1,
    "trans_orange": 3,
    "trans_pink": 1,
    "chrome_silver": 2,
    "copper": 1,
    "flat_silver": 45,
    "pearl_dark_gray": 3,
    "pearl_gold": 5,
    "pearl_light_gold": 1,
    "pearl_sand_blue": 2,
    "metallic_green": 1,
    "metallic_silver": 4
}

piece_2038 = {
    "black": 10,
    "blue": 10,
    "brown": 10,
    "dark_green": 10,
    "dark_pink": 10,
    "green": 10,
    "light_gray": 10,
    "red": 10,
    "reddish_brown": 10,
    "tan": 10,
    "white": 10,
    "yellow": 10,
    "chrome_silver": 10,
    "flat_silver": 10
}

piece_2039 = {
    "black": 10,
    "blue": 10,
    "bright_light_blue": 10,
    "brown": 10,
    "dark_blue": 10,
    "dark_bluish_gray": 10,
    "dark_brown": 10,
    "dark_gray": 10,
    "dark_green": 10,
    "dark_purple": 10,
    "dark_tan": 10,
    "dark_turquoise": 10,
    "green": 10,
    "light_bluish_gray": 10,
    "light_gray": 10,
    "light_turquoise": 10,
    "medium_lavender": 10,
    "pink": 10,
    "red": 10,
    "sand_blue": 10,
    "sand_green": 10,
    "tan": 10,
    "violet": 10,
    "white": 10,
    "yellow": 10,
    "trans_red": 10,
    "flat_silver": 10,
    "pearl_black": 10,
    "pearl_dark_gray": 10,
    "reddish_gold": 10,
    "satin_trans_clear": 10
}

piece_2335 = {
    "aqua": 10,
    "black": 10,
    "blue": 10,
    "bright_green": 10,
    "bright_light_blue": 10,
    "bright_light_orange": 10,
    "bright_light_yellow": 10,
    "bright_pink": 10,
    "brown": 10,
    "dark_azure": 10,
    "dark_blue": 10,
    "dark_blue_violet": 10,
    "dark_bluish_gray": 10,
    "dark_brown": 10,
    "dark_gray": 10,
    "dark_green": 10,
    "dark_orange": 10,
    "dark_pink": 10,
    "dark_purple": 10,
    "dark_red": 10,
    "dark_tan": 10,
    "dark_turquoise": 10,
    "dark_yellow": 10,
    "earth_orange": 10,
    "green": 10,
    "light_aqua": 10,
    "light_bluish_gray": 10,
    "light_brown": 10,
    "light_gray": 10,
    "light_nougat": 10,
    "light_pink": 10,
    "light_purple": 10,
    "light_turquoise": 10,
    "light_yellow": 10,
    "lime": 10,
    "maersk_blue": 10,
    "magenta": 10,
    "medium_azure": 10,
    "medium_blue": 10,
    "medium_lavender": 10,
    "medium_nougat": 10,
    "medium_orange": 10,
    "medium_violet": 10,
    "neon_orange": 10,
    "nougat": 10,
    "olive_green": 10,
    "orange": 10,
    "pink": 10,
    "purple": 10,
    "red": 10,
    "reddish_brown": 10,
    "rust": 10,
    "sand_blue": 10,
    "sand_green": 10,
    "sky_blue": 10,
    "tan": 10,
    "very_light_bluish_gray": 10,
    "very_light_gray": 10,
    "white": 10,
    "yellow": 10,
    "yellowish_green": 10,
    "trans_aqua": 10,
    "trans_brown": 10,
    "trans_clear": 10,
    "trans_dark_blue": 10,
    "trans_light_blue": 10,
    "trans_neon_green": 10,
    "trans_purple": 10,
    "trans_red": 10,
    "chrome_black": 10,
    "chrome_blue": 10,
    "chrome_silver": 10,
    "flat_silver": 10,
    "pearl_dark_gray": 10,
    "pearl_gold": 10,
    "pearl_light_gray": 10,
    "metallic_silver": 10
}

piece_2336 = {
    "black": 16,
    "blue": 8,
    "dark_bluish_gray": 1,
    "dark_gray": 1,
    "green": 2,
    "light_gray": 4,
    "orange": 214,
    "red": 10,
    "tan": 3,
    "white": 14,
    "yellow": 2
}

piece_2338 = {
    "black": 556,
    "blue": 1,
    "brown": 1,
    "green": 1,
    "orange": 3,
    "red": 1025,
    "tan": 2,
    "white": 533,
    "yellow": 2,
    "trans_clear": 2
}

piece_2339 = {
    "black": 28729,
    "blue": 109,
    "bright_green": 1,
    "bright_light_blue": 1,
    "bright_light_orange": 1,
    "bright_light_yellow": 2,
    "brown": 2906,
    "dark_azure": 1,
    "dark_blue": 6315,
    "dark_blue_violet": 1,
    "dark_bluish_gray": 17715,
    "dark_brown": 6488,
    "dark_gray": 278,
    "dark_green": 13,
    "dark_nougat": 2,
    "dark_orange": 9,
    "dark_pink": 1,
    "dark_purple": 62,
    "dark_red": 35,
    "dark_tan": 829,
    "dark_turquoise": 141,
    "earth_orange": 1,
    "fabuland_brown": 15,
    "green": 301,
    "lavender": 128,
    "light_bluish_gray": 32947,
    "light_brown": 9,
    "light_gray": 4904,
    "light_nougat": 2,
    "light_orange": 1,
    "light_pink": 2,
    "light_yellow": 42,
    "medium_blue": 5,
    "medium_brown": 3,
    "medium_lavender": 201,
    "medium_nougat": 750,
    "medium_tan": 1,
    "nougat": 1,
    "olive_green": 3,
    "orange": 4,
    "purple": 1,
    "red": 3342,
    "reddish_brown": 31104,
    "salmon": 1,
    "sand_green": 11,
    "tan": 11701,
    "very_light_bluish_gray": 13,
    "very_light_gray": 5,
    "very_light_orange": 1,
    "white": 10031,
    "yellow": 2214,
    "trans_dark_blue": 2,
    "trans_green": 1,
    "trans_light_orange": 2,
    "chrome_gold": 1,
    "pearl_dark_gray": 7,
    "pearl_gold": 4
}

piece_2340 = {
    "black": 6311,
    "blue": 2849,
    "bright_green": 1,
    "bright_light_blue": 1,
    "bright_light_orange": 121,
    "bright_pink": 1,
    "clikits_lavender": 2,
    "dark_azure": 1,
    "dark_blue": 326,
    "dark_bluish_gray": 1478,
    "dark_gray": 287,
    "dark_green": 5,
    "dark_orange": 204,
    "dark_pink": 1,
    "dark_purple": 2,
    "dark_red": 129,
    "dark_tan": 2,
    "dark_turquoise": 382,
    "green": 11,
    "light_aqua": 1,
    "light_bluish_gray": 1657,
    "light_gray": 1129,
    "magenta": 131,
    "medium_azure": 381,
    "medium_lime": 1,
    "medium_nougat": 1,
    "olive_green": 1,
    "orange": 313,
    "red": 2694,
    "reddish_brown": 78,
    "sand_blue": 1,
    "sand_green": 1,
    "sky_blue": 1,
    "tan": 6,
    "very_light_bluish_gray": 10,
    "white": 5980,
    "yellow": 580,
    "trans_clear": 29,
    "trans_green": 1,
    "trans_neon_yellow": 1,
    "trans_orange": 1,
    "pearl_dark_gray": 1,
    "milky_white": 1
}

piece_2341 = {
    "black": 4719,
    "blue": 30,
    "bright_green": 1,
    "bright_light_orange": 3,
    "brown": 46,
    "dark_azure": 2,
    "dark_blue": 25,
    "dark_blue_violet": 1,
    "dark_bluish_gray": 11866,
    "dark_brown": 23,
    "dark_gray": 58,
    "dark_green": 7,
    "dark_orange": 2,
    "dark_pink": 2,
    "dark_purple": 128,
    "dark_red": 1072,
    "dark_tan": 11,
    "earth_orange": 16,
    "fabuland_brown": 16,
    "fabuland_orange": 1,
    "green": 9,
    "light_aqua": 23,
    "light_blue": 1,
    "light_bluish_gray": 24589,
    "light_brown": 4,
    "light_gray": 1835,
    "light_green": 16,
    "light_nougat": 6,
    "lime": 3,
    "magenta": 1,
    "medium_azure": 312,
    "medium_blue": 4,
    "medium_nougat": 2,
    "medium_orange": 1,
    "olive_green": 2,
    "orange": 27,
    "purple": 1,
    "red": 2086,
    "reddish_brown": 75,
    "rust": 2,
    "sand_blue": 2,
    "sand_green": 11,
    "tan": 2740,
    "very_light_bluish_gray": 15,
    "very_light_gray": 5,
    "white": 4822,
    "yellow": 207,
    "trans_bright_green": 2,
    "chrome_black": 2,
    "chrome_gold": 2,
    "chrome_silver": 6,
    "copper": 4,
    "flat_silver": 3,
    "pearl_dark_gray": 3,
    "pearl_gold": 2,
    "metallic_silver": 3,
    "glow_in_dark_white": 4,
}

piece_2342 = {
    "black": 3751,
    "blue": 745,
    "bright_light_yellow": 2,
    "brown": 15,
    "dark_bluish_gray": 96,
    "dark_brown": 21,
    "dark_gray": 846,
    "dark_green": 1,
    "dark_red": 7,
    "dark_tan": 20,
    "dark_turquoise": 339,
    "green": 31,
    "light_bluish_gray": 78,
    "light_gray": 1663,
    "light_nougat": 1,
    "orange": 1,
    "red": 405,
    "reddish_brown": 6,
    "sand_blue": 1,
    "tan": 29,
    "very_light_bluish_gray": 3,
    "white": 2703,
    "yellow": 764,
    "flat_silver": 2,
    "pearl_black": 1,
    "pearl_dark_gray": 7
}

piece_3245b = {
    "aqua": 5,
    "black": 4867,
    "blue": 199,
    "blue_violet": 8,
    "bright_green": 37,
    "bright_light_blue": 11,
    "bright_light_orange": 52,
    "bright_light_yellow": 25,
    "bright_pink": 2,
    "brown": 123,
    "clikits_lavender": 3,
    "dark_azure": 12,
    "dark_blue": 1303,
    "dark_blue_violet": 12,
    "dark_bluish_gray": 9121,
    "dark_brown": 106,
    "dark_gray": 425,
    "dark_green": 67,
    "dark_nougat": 1,
    "dark_orange": 44,
    "dark_pink": 4,
    "dark_purple": 10,
    "dark_red": 135,
    "dark_tan": 130,
    "dark_turquoise": 533,
    "dark_yellow": 6,
    "earth_orange": 4,
    "fabuland_brown": 20,
    "fabuland_orange": 9,
    "green": 81,
    "lavender": 3,
    "light_blue": 6,
    "light_bluish_gray": 15937,
    "light_brown": 50,
    "light_gray": 4975,
    "light_green": 5,
    "light_lime": 15,
    "light_nougat": 33,
    "light_orange": 2,
    "light_pink": 1,
    "light_salmon": 1,
    "light_yellow": 14,
    "lilac": 1,
    "lime": 9,
    "maersk_blue": 4,
    "magenta": 5,
    "medium_azure": 17,
    "medium_blue": 170,
    "medium_brown": 10,
    "medium_dark_pink": 2,
    "medium_green": 4,
    "medium_lavender": 106,
    "medium_lime": 2,
    "medium_nougat": 40,
    "medium_orange": 12,
    "medium_tan": 6,
    "neon_green": 2,
    "neon_orange": 48,
    "neon_yellow": 128,
    "nougat": 43,
    "olive_green": 18,
    "orange": 879,
    "pink": 11,
    "purple": 6,
    "red": 4453,
    "reddish_brown": 1798,
    "rust": 25,
    "salmon": 2,
    "sand_blue": 17,
    "sand_green": 65,
    "sand_purple": 1,
    "sky_blue": 4,
    "tan": 7749,
    "very_light_bluish_gray": 42,
    "very_light_gray": 24,
    "very_light_orange": 9,
    "violet": 4,
    "white": 20930,
    "yellow": 5984,
    "yellowish_green": 2,
    "trans_aqua": 2,
    "trans_black": 6,
    "trans_brown": 18,
    "trans_clear": 49,
    "trans_dark_blue": 7,
    "trans_light_blue": 10,
    "trans_medium_blue": 1,
    "trans_neon_orange": 1,
    "trans_red": 2,
    "trans_yellow": 1,
    "chrome_antique_brass": 1,
    "chrome_gold": 1,
    "chrome_green": 1,
    "chrome_silver": 9,
    "copper": 1,
    "flat_silver": 98,
    "pearl_black": 4,
    "pearl_dark_gray": 11,
    "pearl_gold": 11,
    "pearl_light_gray": 11,
    "pearl_very_light_gray": 1,
    "pearl_white": 2,
    "metallic_copper": 1,
    "metallic_silver": 17,
    "glow_in_dark_white": 8,
    "glitter_trans_clear": 1
}

piece_3245c = {
    "Aqua": 5,
    "Black": 48785,
    "Blue": 3792,
    "Blue-Violet": 8,
    "Bright Green": 2409,
    "Bright Light Blue": 10,
    "Bright Light Orange": 663,
    "Bright Light Yellow": 9,
    "Bright Pink": 66,
    "Brown": 76,
    "Clikits Lavender": 1,
    "Dark Azure": 732,
    "Dark Blue": 163,
    "Dark Blue-Violet": 8,
    "Dark Bluish Gray": 46065,
    "Dark Brown": 50,
    "Dark Gray": 101,
    "Dark Green": 136,
    "Dark Nougat": 5,
    "Dark Orange": 17,
    "Dark Pink": 14,
    "Dark Purple": 20,
    "Dark Red": 3723,
    "Dark Tan": 108,
    "Dark Turquoise": 166,
    "Dark Yellow": 1,
    "Earth Orange": 7,
    "Fabuland Brown": 10,
    "Fabuland Orange": 9,
    "Green": 1704,
    "Lavender": 11,
    "Light Aqua": 6,
    "Light Blue": 3,
    "Light Bluish Gray": 70222,
    "Light Brown": 14,
    "Light Gray": 362,
    "Light Green": 1,
    "Light Nougat": 20,
    "Light Pink": 2,
    "Light Purple": 2,
    "Light Salmon": 2,
    "Light Turquoise": 1,
    "Light Yellow": 18,
    "Lime": 359,
    "Maersk Blue": 2,
    "Magenta": 55,
    "Medium Azure": 12,
    "Medium Blue": 462,
    "Medium Brown": 6,
    "Medium Dark Pink": 1,
    "Medium Green": 5,
    "Medium Lavender": 416,
    "Medium Lime": 3,
    "Medium Nougat": 342,
    "Medium Orange": 3,
    "Medium Tan": 3,
    "Medium Violet": 1,
    "Nougat": 45,
    "Olive Green": 29,
    "Orange": 2797,
    "Pink": 4,
    "Purple": 3,
    "Red": 16986,
    "Reddish Brown": 15077,
    "Rust": 18,
    "Salmon": 3,
    "Sand Blue": 81,
    "Sand Green": 4554,
    "Sand Red": 2,
    "Sky Blue": 4,
    "Tan": 36394,
    "Very Light Bluish Gray": 56,
    "Very Light Gray": 10,
    "Very Light Orange": 1,
    "Violet": 2,
    "White": 53693,
    "Yellow": 8564,
    "Trans-Aqua": 2,
    "Trans-Black (2023)": 1,
    "Trans-Brown (Old Trans-Black)": 49,
    "Trans-Clear": 48,
    "Trans-Dark Blue": 2,
    "Trans-Light Blue": 53,
    "Trans-Medium Blue": 7,
    "Trans-Neon Green": 1,
    "Trans-Orange": 1,
    "Trans-Red": 2,
    "Trans-Yellow": 1,
    "Chrome Black": 1,
    "Chrome Gold": 1,
    "Chrome Silver": 9,
    "Copper": 2,
    "Flat Silver": 19,
    "Pearl Black": 1,
    "Pearl Dark Gray": 24,
    "Pearl Gold": 7,
    "Pearl Light Gray": 1,
    "Pearl Sand Blue": 1,
    "Pearl White": 2,
    "Metallic Gold": 2,
    "Metallic Silver": 9,
    "Glow In Dark White": 2,
    "Milky White": 1,
}

piece_2453a = {
    "aqua": 5,
    "black": 9623,
    "blue": 717,
    "blue_violet": 3,
    "bright_green": 10,
    "bright_light_blue": 5,
    "bright_light_orange": 10,
    "bright_light_yellow": 35,
    "brown": 808,
    "clikits_lavender": 2,
    "dark_azure": 1,
    "dark_blue": 22,
    "dark_blue_violet": 2,
    "dark_bluish_gray": 7129,
    "dark_brown": 66,
    "dark_gray": 518,
    "dark_green": 535,
    "dark_nougat": 5,
    "dark_orange": 420,
    "dark_pink": 107,
    "dark_purple": 21,
    "dark_red": 2152,
    "dark_tan": 81,
    "dark_turquoise": 19,
    "dark_yellow": 3,
    "earth_orange": 1,
    "fabuland_brown": 18,
    "fabuland_orange": 2,
    "green": 38,
    "lavender": 6,
    "light_aqua": 2,
    "light_blue": 1,
    "light_bluish_gray": 8860,
    "light_brown": 46,
    "light_gray": 4574,
    "light_lime": 1,
    "light_nougat": 7,
    "light_orange": 3,
    "light_pink": 1,
    "light_purple": 2,
    "light_salmon": 1,
    "light_turquoise": 2,
    "light_yellow": 165,
    "lime": 5,
    "maersk_blue": 6,
    "magenta": 18,
    "medium_azure": 8,
    "medium_blue": 12,
    "medium_brown": 4,
    "medium_green": 3,
    "medium_lavender": 2,
    "medium_lime": 1,
    "medium_nougat": 125,
    "medium_orange": 4,
    "medium_tan": 6,
    "neon_green": 1,
    "nougat": 14,
    "olive_green": 4,
    "orange": 313,
    "pink": 1,
    "purple": 1,
    "red": 3068,
    "reddish_brown": 4844,
    "rust": 11,
    "sand_blue": 17,
    "sand_green": 70,
    "sky_blue": 6,
    "tan": 5556,
    "very_light_bluish_gray": 29,
    "very_light_gray": 28,
    "very_light_orange": 7,
    "violet": 4,
    "white": 12584,
    "yellow": 2109,
    "trans_brown": 10,
    "trans_clear": 109,
    "trans_dark_blue": 3,
    "trans_dark_pink": 2,
    "trans_light_blue": 16,
    "trans_medium_blue": 16,
    "trans_neon_orange": 1,
    "trans_orange": 1,
    "trans_yellow": 1,
    "chrome_black": 2,
    "chrome_gold": 3,
    "chrome_silver": 3,
    "copper": 4,
    "flat_dark_gold": 1,
    "flat_silver": 30,
    "pearl_black": 2,
    "pearl_dark_gray": 7,
    "pearl_gold": 10,
    "pearl_light_gold": 1,
    "pearl_light_gray": 3,
    "pearl_white": 1,
    "metallic_gold": 1,
    "metallic_silver": 10,
    "glow_in_dark_white": 4,
}

piece_2453b = {
    "aqua": 4,
    "black": 16164,
    "blue": 566,
    "blue_violet": 5,
    "bright_green": 12,
    "bright_light_blue": 12,
    "bright_light_orange": 1005,
    "bright_light_yellow": 1559,
    "bright_pink": 564,
    "brown": 256,
    "clikits_lavender": 2,
    "dark_azure": 7,
    "dark_blue": 33,
    "dark_blue_violet": 7,
    "dark_bluish_gray": 18064,
    "dark_brown": 295,
    "dark_gray": 129,
    "dark_green": 59,
    "dark_nougat": 6,
    "dark_orange": 63,
    "dark_pink": 4,
    "dark_purple": 319,
    "dark_red": 2592,
    "dark_salmon": 1,
    "dark_tan": 124,
    "dark_turquoise": 305,
    "dark_yellow": 1,
    "earth_orange": 4,
    "fabuland_brown": 63,
    "fabuland_lime": 2,
    "fabuland_orange": 4,
    "green": 85,
    "lavender": 107,
    "light_aqua": 600,
    "light_blue": 5,
    "light_bluish_gray": 32322,
    "light_brown": 40,
    "light_gray": 340,
    "light_green": 1,
    "light_lime": 1,
    "light_nougat": 48,
    "light_orange": 4,
    "light_pink": 1,
    "light_purple": 2,
    "light_turquoise": 4,
    "light_yellow": 21,
    "lime": 48,
    "maersk_blue": 1,
    "magenta": 127,
    "medium_azure": 305,
    "medium_blue": 14,
    "medium_brown": 6,
    "medium_green": 4,
    "medium_lavender": 1,
    "medium_lime": 2,
    "medium_nougat": 3376,
    "medium_orange": 2,
    "medium_tan": 12,
    "neon_green": 1,
    "neon_orange": 4,
    "neon_yellow": 2,
    "nougat": 24,
    "olive_green": 3,
    "orange": 133,
    "pink": 2,
    "purple": 8,
    "red": 5098,
    "reddish_brown": 27722,
    "rust": 21,
    "salmon": 1,
    "sand_blue": 68,
    "sand_green": 1898,
    "sand_red": 1,
    "sky_blue": 7,
    "tan": 26492,
    "very_light_bluish_gray": 14,
    "very_light_gray": 37,
    "very_light_orange": 4,
    "violet": 1,
    "white": 37376,
    "yellow": 3075,
    "yellowish_green": 76,
    "trans_aqua": 1,
    "trans_black": 2,
    "trans_bright_green": 1,
    "trans_brown": 19,
    "trans_clear": 86,
    "trans_dark_blue": 4,
    "trans_light_blue": 19,
    "trans_light_purple": 1,
    "trans_medium_blue": 35,
    "trans_neon_orange": 2,
    "trans_neon_yellow": 3,
    "trans_orange": 1,
    "trans_red": 1,
    "trans_yellow": 16,
    "chrome_antique_brass": 1,
    "chrome_black": 1,
    "chrome_gold": 4,
    "chrome_silver": 4,
    "copper": 3,
    "flat_silver": 48,
    "pearl_black": 7,
    "pearl_dark_gray": 6,
    "pearl_gold": 82,
    "pearl_light_gray": 3,
    "pearl_white": 2,
    "satin_trans_clear": 1,
    "metallic_copper": 2,
    "metallic_gold": 4,
    "metallic_green": 1,
    "metallic_silver": 4,
    "glow_in_dark_white": 7,
}

piece_2454 = {
    "aqua": 10,
    "black": 36398,
    "blue": 4131,
    "blue_violet": 218,
    "bright_green": 13,
    "bright_light_blue": 45,
    "bright_light_orange": 114,
    "bright_light_yellow": 1288,
    "bright_pink": 171,
    "brown": 675,
    "clikits_lavender": 2,
    "coral": 1,
    "dark_azure": 8,
    "dark_blue": 784,
    "dark_blue_violet": 7,
    "dark_bluish_gray": 35019,
    "dark_brown": 43,
    "dark_gray": 2924,
    "dark_green": 379,
    "dark_nougat": 4,
    "dark_orange": 978,
    "dark_pink": 13,
    "dark_purple": 525,
    "dark_red": 2206,
    "dark_salmon": 1,
    "dark_tan": 256,
    "dark_turquoise": 8,
    "dark_yellow": 3,
    "earth_orange": 8,
    "fabuland_brown": 17,
    "fabuland_orange": 1,
    "green": 841,
    "lavender": 1402,
    "light_aqua": 879,
    "light_blue": 5,
    "light_bluish_gray": 41640,
    "light_brown": 18,
    "light_gray": 5412,
    "light_green": 4,
    "light_lime": 2,
    "light_nougat": 109,
    "light_orange": 2,
    "light_pink": 2,
    "light_purple": 1,
    "light_salmon": 2,
    "light_turquoise": 4,
    "light_yellow": 275,
    "lime": 44,
    "maersk_blue": 4,
    "magenta": 1125,
    "medium_azure": 178,
    "medium_blue": 19,
    "medium_brown": 1,
    "medium_green": 3,
    "medium_lavender": 367,
    "medium_lime": 2,
    "medium_nougat": 3610,
    "medium_orange": 840,
    "medium_tan": 7,
    "medium_violet": 56,
    "neon_orange": 3,
    "nougat": 40,
    "olive_green": 358,
    "orange": 388,
    "pink": 3,
    "purple": 4,
    "red": 11548,
    "reddish_brown": 13347,
    "rust": 4,
    "salmon": 1,
    "sand_blue": 71,
    "sand_green": 2058,
    "sand_purple": 12,
    "sand_red": 2,
    "sky_blue": 15,
    "tan": 47243,
    "very_light_bluish_gray": 69,
    "very_light_gray": 18,
    "very_light_orange": 7,
    "violet": 3,
    "white": 52843,
    "yellow": 3367,
    "yellowish_green": 1,
    "trans_aqua": 1,
    "trans_black": 101,
    "trans_clear": 871,
    "trans_dark_blue": 62,
    "trans_dark_pink": 9,
    "trans_light_blue": 334,
    "trans_light_orange": 4,
    "trans_medium_blue": 41,
    "trans_neon_green": 18,
    "trans_neon_orange": 3,
    "trans_orange": 27,
    "trans_purple": 3,
    "trans_red": 8,
    "trans_yellow": 3,
    "chrome_black": 3,
    "chrome_gold": 5,
    "chrome_silver": 3,
    "copper": 2,
    "flat_silver": 39,
    "pearl_dark_gray": 19,
    "pearl_gold": 8,
    "pearl_light_gray": 1,
    "satin_trans_clear": 1,
    "satin_trans_light_blue": 1,
    "metallic_gold": 1,
    "metallic_silver": 10,
    "glow_in_dark_white": 12,
    "milky_white": 1,
}

piece_22886 = {
    "aqua": 3,
    "black": 2824,
    "blue": 87,
    "blue_violet": 2,
    "bright_green": 17,
    "bright_light_blue": 8,
    "bright_light_orange": 139,
    "bright_light_yellow": 17,
    "bright_pink": 68,
    "brown": 93,
    "clikits_lavender": 1,
    "coral": 3,
    "dark_azure": 12,
    "dark_blue": 129,
    "dark_blue_violet": 6,
    "dark_bluish_gray": 1740,
    "dark_brown": 94,
    "dark_gray": 105,
    "dark_green": 82,
    "dark_nougat": 1,
    "dark_orange": 1219,
    "dark_pink": 2,
    "dark_purple": 11,
    "dark_red": 81,
    "dark_tan": 2502,
    "dark_turquoise": 17,
    "dark_yellow": 1,
    "earth_orange": 8,
    "fabuland_brown": 14,
    "fabuland_orange": 3,
    "green": 163,
    "light_aqua": 267,
    "light_blue": 4,
    "light_bluish_gray": 19145,
    "light_brown": 33,
    "light_gray": 335,
    "light_nougat": 20,
    "light_orange": 3,
    "light_pink": 2,
    "light_purple": 1,
    "light_salmon": 10,
    "light_turquoise": 4,
    "light_violet": 5,
    "light_yellow": 58,
    "lime": 4,
    "maersk_blue": 1,
    "magenta": 4,
    "medium_azure": 7,
    "medium_blue": 299,
    "medium_brown": 9,
    "medium_dark_pink": 2,
    "medium_green": 3,
    "medium_lavender": 5,
    "medium_lime": 1,
    "medium_nougat": 31,
    "medium_orange": 17,
    "medium_tan": 3,
    "medium_violet": 1,
    "nougat": 17,
    "olive_green": 44,
    "orange": 29,
    "pink": 4,
    "purple": 3,
    "red": 221,
    "reddish_brown": 626,
    "rust": 14,
    "salmon": 3,
    "sand_blue": 76,
    "sand_green": 920,
    "sky_blue": 8,
    "tan": 770,
    "very_light_bluish_gray": 91,
    "very_light_gray": 17,
    "very_light_orange": 7,
    "white": 15839,
    "yellow": 1162,
    "trans_aqua": 24,
    "trans_black": 2,
    "trans_brown": 21,
    "trans_clear": 84,
    "trans_dark_blue": 2,
    "trans_light_blue": 16,
    "trans_light_green": 1,
    "trans_light_orange": 1,
    "trans_medium_blue": 25,
    "trans_neon_green": 1,
    "trans_neon_orange": 1,
    "trans_neon_yellow": 1,
    "trans_orange": 3,
    "trans_red": 3,
    "trans_yellow": 1,
    "chrome_black": 7,
    "chrome_gold": 12,
    "chrome_silver": 1,
    "copper": 1,
    "flat_dark_gold": 2,
    "flat_silver": 88,
    "pearl_black": 1,
    "pearl_dark_gray": 19,
    "pearl_gold": 4,
    "pearl_light_gray": 8,
    "pearl_very_light_gray": 1,
    "metallic_gold": 2,
    "metallic_green": 2,
    "metallic_silver": 9,
    "glow_in_dark_white": 9
}

piece_3001 = {
    "aqua": 10,
    "black": 10,
    "blue": 10,
    "blue_violet": 10,
    "bright_green": 10,
    "bright_light_blue": 10,
    "bright_light_orange": 10,
    "bright_light_yellow": 10,
    "bright_pink": 10,
    "brown": 10,
    "clikits_lavender": 10,
    "coral": 10,
    "dark_azure": 10,
    "dark_blue": 10,
    "dark_blue_violet": 10,
    "dark_bluish_gray": 10,
    "dark_brown": 10,
    "dark_gray": 10,
    "dark_green": 10,
    "dark_nougat": 10,
    "dark_olive_green": 10,
    "dark_orange": 10,
    "dark_pink": 10,
    "dark_purple": 10,
    "dark_red": 10,
    "dark_salmon": 10,
    "dark_tan": 10,
    "dark_turquoise": 10,
    "dark_yellow": 10,
    "earth_orange": 10,
    "fabuland_brown": 10,
    "fabuland_lime": 10,
    "fabuland_orange": 10,
    "green": 10,
    "lavender": 10,
    "light_aqua": 10,
    "light_blue": 10,
    "light_bluish_gray": 10,
    "light_brown": 10,
    "light_gray": 10,
    "light_green": 10,
    "light_lilac": 10,
    "light_lime": 10,
    "light_nougat": 10,
    "light_orange": 10,
    "light_pink": 10,
    "light_purple": 10,
    "light_salmon": 10,
    "light_turquoise": 10,
    "light_violet": 10,
    "light_yellow": 10,
    "lilac": 10,
    "lime": 10,
    "little_robots_blue": 10,
    "maersk_blue": 10,
    "magenta": 10,
    "medium_azure": 10,
    "medium_blue": 10,
    "medium_brown": 10,
    "medium_dark_pink": 10,
    "medium_green": 10,
    "medium_lavender": 10,
    "medium_lime": 10,
    "medium_nougat": 10,
    "medium_orange": 10,
    "medium_tan": 10,
    "medium_violet": 10,
    "neon_green": 10,
    "neon_orange": 10,
    "neon_yellow": 10,
    "nougat": 10,
    "olive_green": 10,
    "orange": 10,
    "pink": 10,
    "purple": 10,
    "red": 10,
    "reddish_brown": 10,
    "rust": 10,
    "salmon": 10,
    "sand_blue": 10,
    "sand_green": 10,
    "sand_purple": 10,
    "sand_red": 10,
    "sky_blue": 10,
    "tan": 10,
    "very_light_bluish_gray": 10,
    "very_light_gray": 10,
    "very_light_orange": 10,
    "violet": 10,
    "white": 10,
    "yellow": 10,
    "yellowish_green": 10,
    "trans_aqua": 10,
    "trans_black": 10,
    "trans_bright_green": 10,
    "trans_brown": 10,
    "trans_clear": 10,
    "trans_dark_blue": 10,
    "trans_dark_pink": 10,
    "trans_green": 10,
    "trans_light_blue": 10,
    "trans_light_bright_green": 10,
    "trans_light_green": 10,
    "trans_light_orange": 10,
    "trans_light_purple": 10,
    "trans_medium_blue": 10,
    "trans_medium_purple": 10,
    "trans_neon_green": 10,
    "trans_neon_orange": 10,
    "trans_neon_yellow": 10,
    "trans_orange": 10,
    "trans_pink": 10,
    "trans_purple": 10,
    "trans_red": 10,
    "trans_yellow": 10,
    "chrome_antique_brass": 10,
    "chrome_black": 10,
    "chrome_blue": 10,
    "chrome_gold": 10,
    "chrome_green": 10,
    "chrome_pink": 10,
    "chrome_silver": 10,
    "bionicle_copper": 10,
    "bionicle_gold": 10,
    "bionicle_silver": 10,
    "copper": 10,
    "flat_dark_gold": 10,
    "flat_silver": 10,
    "pearl_black": 10,
    "pearl_blue": 10,
    "pearl_brown": 10,
    "pearl_dark_gray": 10,
    "pearl_gold": 10,
    "pearl_green": 10,
    "pearl_light_gold": 10,
    "pearl_light_gray": 10,
    "pearl_red": 10,
    "pearl_sand_blue": 10,
    "pearl_sand_purple": 10,
    "pearl_very_light_gray": 10,
    "pearl_white": 10,
    "reddish_copper": 10,
    "reddish_gold": 10,
    "satin_trans_bright_green": 10,
    "satin_trans_brown": 10,
    "satin_trans_clear": 10,
    "satin_trans_dark_blue": 10,
    "satin_trans_dark_pink": 10,
    "satin_trans_light_blue": 10,
    "satin_trans_purple": 10,
    "metallic_copper": 10,
    "metallic_gold": 10,
    "metallic_green": 10,
    "metallic_silver": 10,
    "glow_in_dark_opaque": 10,
    "glow_in_dark_trans": 10,
    "glow_in_dark_white": 10,
    "milky_white": 10,
    "glitter_trans_clear": 10,
    "glitter_trans_dark_pink": 10,
    "glitter_trans_light_blue": 10,
    "glitter_trans_neon_green": 10,
    "glitter_trans_orange": 10,
    "glitter_trans_purple": 10,
}

piece_3004 = {
    "Aqua": 363,
    "Black": 434623,
    "Blue": 98063,
    "Blue-Violet": 617,
    "Bright Green": 6075,
    "Bright Light Blue": 9528,
    "Bright Light Orange": 17693,
    "Bright Light Yellow": 9646,
    "Bright Pink": 13486,
    "Brown": 18208,
    "Clikits Lavender": 60,
    "Coral": 2389,
    "Dark Azure": 12518,
    "Dark Blue": 55611,
    "Dark Blue-Violet": 141,
    "Dark Bluish Gray": 316305,
    "Dark Brown": 17039,
    "Dark Gray": 14675,
    "Dark Green": 52767,
    "Dark Nougat": 244,
    "Dark Olive Green": 8,
    "Dark Orange": 28482,
    "Dark Pink": 6476,
    "Dark Purple": 10613,
    "Dark Red": 94773,
    "Dark Salmon": 9,
    "Dark Tan": 85960,
    "Dark Turquoise": 7473,
    "Dark Yellow": 91,
    "Earth Orange": 283,
    "Fabuland Brown": 396,
    "Fabuland Lime": 11,
    "Fabuland Orange": 39,
    "Green": 47799,
    "Lavender": 4274,
    "Light Aqua": 5466,
    "Light Blue": 254,
    "Light Bluish Gray": 428335,
    "Light Brown": 689,
    "Light Gray": 45459,
    "Light Green": 217,
    "Light Lilac": 1,
    "Light Lime": 170,
    "Light Nougat": 2098,
    "Light Orange": 218,
    "Light Pink": 189,
    "Light Purple": 392,
    "Light Salmon": 109,
    "Light Turquoise": 169,
    "Light Violet": 92,
    "Light Yellow": 1044,
    "Lilac": 22,
    "Lime": 28359,
    "Little Robots Blue": 3,
    "Maersk Blue": 1480,
    "Magenta": 5121,
    "Medium Azure": 11999,
    "Medium Blue": 32338,
    "Medium Brown": 120,
    "Medium Dark Pink": 196,
    "Medium Green": 553,
    "Medium Lavender": 6494,
    "Medium Lime": 124,
    "Medium Nougat": 39299,
    "Medium Orange": 224,
    "Medium Tan": 83,
    "Medium Violet": 162,
    "Neon Green": 86,
    "Neon Orange": 43,
    "Neon Yellow": 320,
    "Nougat": 1504,
    "Olive Green": 17194,
    "Orange": 38084,
    "Pink": 1094,
    "Purple": 1139,
    "Red": 171229,
    "Reddish Brown": 157202,
    "Rust": 233,
    "Salmon": 62,
    "Sand Blue": 10893,
    "Sand Green": 30272,
    "Sand Purple": 116,
    "Sand Red": 741,
    "Sky Blue": 247,
    "Tan": 212460,
    "Very Light Bluish Gray": 1682,
    "Very Light Gray": 385,
    "Very Light Orange": 131,
    "Violet": 99,
    "White": 371791,
    "Yellow": 100035,
    "Yellowish Green": 2901,
    "Trans-Aqua": 166,
    "Trans-Black": 2023,
    "Trans-Bright Green": 177,
    "Trans-Brown (Old Trans-Black)": 1424,
    "Trans-Clear": 23577,
    "Trans-Dark Blue": 615,
    "Trans-Dark Pink": 173,
    "Trans-Green": 253,
    "Trans-Light Blue": 843,
    "Trans-Light Bright Green": 72,
    "Trans-Light Green": 65,
    "Trans-Light Orange": 68,
    "Trans-Light Purple": 38,
    "Trans-Medium Blue": 257,
    "Trans-Medium Purple": 22,
    "Trans-Neon Green": 181,
    "Trans-Neon Orange": 193,
    "Trans-Neon Yellow": 144,
    "Trans-Orange": 152,
    "Trans-Pink": 143,
    "Trans-Purple": 180,
    "Trans-Red": 949,
    "Trans-Yellow": 482,
    "Chrome Antique Brass": 14,
    "Chrome Black": 39,
    "Chrome Blue": 20,
    "Chrome Gold": 177,
    "Chrome Green": 15,
    "Chrome Pink": 13,
    "Chrome Silver": 476,
    "Bionicle Copper": 4,
    "Bionicle Gold": 4,
    "Bionicle Silver": 4,
    "Copper": 79,
    "Flat Dark Gold": 64,
    "Flat Silver": 474,
    "Pearl Black": 29,
    "Pearl Dark Gray": 413,
    "Pearl Gold": 193,
    "Pearl Light Gold": 56,
    "Pearl Light Gray": 288,
    "Pearl Sand Blue": 52,
    "Pearl Very Light Gray": 36,
    "Pearl White": 27,
    "Reddish Gold": 10,
    "Satin Trans-Bright Green": 10,
    "Satin Trans-Brown": 15,
    "Satin Trans-Clear": 32,
    "Satin Trans-Dark Blue": 26,
    "Satin Trans-Dark Pink": 8,
    "Satin Trans-Light Blue": 11,
    "Satin Trans-Purple": 5,
    "Metallic Copper": 1,
    "Metallic Gold": 106,
    "Metallic Green": 34,
    "Metallic Silver": 260,
    "Glow In Dark Opaque": 55,
    "Glow In Dark Trans": 18,
    "Glow In Dark White": 116,
    "Milky White": 55,
    "Glitter Trans-Clear": 13,
    "Glitter Trans-Dark Pink": 91,
    "Glitter Trans-Light Blue": 48,
    "Glitter Trans-Neon Green": 28,
    "Glitter Trans-Orange": 6,
    "Glitter Trans-Purple": 35,
}

piece_3005 = {
    "aqua": 511,
    "black": 367667,
    "blue": 74319,
    "blue_violet": 132,
    "bright_green": 1894,
    "bright_light_blue": 4068,
    "bright_light_orange": 15019,
    "bright_light_yellow": 5991,
    "bright_pink": 9843,
    "brown": 13340,
    "clikits_lavender": 43,
    "coral": 1481,
    "dark_azure": 8170,
    "dark_blue": 51120,
    "dark_blue_violet": 131,
    "dark_bluish_gray": 283596,
    "dark_brown": 12186,
    "dark_gray": 9945,
    "dark_green": 48054,
    "dark_nougat": 233,
    "dark_olive_green": 9,
    "dark_orange": 29396,
    "dark_pink": 6909,
    "dark_purple": 8934,
    "dark_red": 81461,
    "dark_salmon": 10,
    "dark_tan": 69761,
    "dark_turquoise": 7111,
    "dark_yellow": 60,
    "earth_orange": 201,
    "fabuland_brown": 435,
    "fabuland_lime": 13,
    "fabuland_orange": 46,
    "green": 36820,
    "lavender": 4709,
    "light_aqua": 2753,
    "light_blue": 189,
    "light_bluish_gray": 393736,
    "light_brown": 679,
    "light_gray": 37599,
    "light_green": 129,
    "light_lilac": 4,
    "light_lime": 37,
    "light_nougat": 2428,
    "light_orange": 195,
    "light_pink": 139,
    "light_purple": 147,
    "light_salmon": 69,
    "light_turquoise": 89,
    "light_violet": 98,
    "light_yellow": 580,
    "lilac": 26,
    "lime": 23066,
    "little_robots_blue": 4,
    "maersk_blue": 1553,
    "magenta": 5406,
    "medium_azure": 12131,
    "medium_blue": 30936,
    "medium_brown": 141,
    "medium_dark_pink": 106,
    "medium_green": 500,
    "medium_lavender": 5271,
    "medium_lime": 93,
    "medium_nougat": 57192,
    "medium_orange": 840,
    "medium_tan": 89,
    "medium_violet": 56,
    "neon_green": 41,
    "neon_orange": 48,
    "neon_yellow": 128,
    "nougat": 1453,
    "olive_green": 18343,
    "orange": 31475,
    "pink": 1316,
    "purple": 391,
    "red": 140657,
    "reddish_brown": 157059,
    "rust": 228,
    "salmon": 62,
    "sand_blue": 19700,
    "sand_green": 39802,
    "sand_purple": 49,
    "sand_red": 59,
    "sky_blue": 110,
    "tan": 186337,
    "very_light_bluish_gray": 721,
    "very_light_gray": 385,
    "very_light_orange": 102,
    "violet": 71,
    "white": 332619,
    "yellow": 78337,
    "yellowish_green": 1339,
    "trans_aqua": 180,
    "trans_black": 2023,
    "trans_bright_green": 235,
    "trans_brown": 21538,
    "trans_clear": 70234,
    "trans_dark_blue": 9080,
    "trans_dark_pink": 3389,
    "trans_green": 2493,
    "trans_light_blue": 12490,
    "trans_light_bright_green": 33,
    "trans_light_green": 17,
    "trans_light_orange": 159,
    "trans_light_purple": 72,
    "trans_medium_blue": 1166,
    "trans_medium_purple": 11,
    "trans_neon_green": 134,
    "trans_neon_orange": 960,
    "trans_neon_yellow": 83,
    "trans_orange": 16360,
    "trans_pink": 121,
    "trans_purple": 4838,
    "trans_red": 5419,
    "trans_yellow": 4531,
    "chrome_antique_brass": 21,
    "chrome_black": 39,
    "chrome_blue": 20,
    "chrome_gold": 159,
    "chrome_green": 14,
    "chrome_pink": 12,
    "chrome_silver": 447,
    "bionicle_copper": 6,
    "bionicle_gold": 7,
    "bionicle_silver": 9,
    "copper": 90,
    "flat_dark_gold": 106,
    "flat_silver": 531,
    "pearl_black": 29,
    "pearl_dark_gray": 553,
    "pearl_gold": 244,
    "pearl_light_gold": 61,
    "pearl_light_gray": 311,
    "pearl_sand_blue": 26,
    "pearl_sand_purple": 3,
    "pearl_very_light_gray": 27,
    "pearl_white": 41,
    "reddish_copper": 2,
    "reddish_gold": 10,
    "satin_trans_bright_green": 14,
    "satin_trans_brown": 13,
    "satin_trans_clear": 31,
    "satin_trans_dark_blue": 30,
    "satin_trans_dark_pink": 10,
    "satin_trans_light_blue": 31,
    "satin_trans_purple": 7,
    "metallic_copper": 2,
    "metallic_gold": 103,
    "metallic_green": 33,
    "metallic_silver": 332,
    "glow_in_dark_opaque": 79,
    "glow_in_dark_trans": 20,
    "glow_in_dark_white": 177,
    "milky_white": 67,
    "glitter_trans_clear": 14,
    "glitter_trans_dark_pink": 1933,
    "glitter_trans_light_blue": 10,
    "glitter_trans_neon_green": 33,
    "glitter_trans_orange": 10,
    "glitter_trans_purple": 1432, 
}

piece_3065 = {
    "aqua": 56,
    "black": 7332,
    "blue": 1175,
    "blue_violet": 45,
    "bright_green": 114,
    "bright_light_blue": 92,
    "bright_light_orange": 87,
    "bright_light_yellow": 95,
    "bright_pink": 62,
    "brown": 348,
    "clikits_lavender": 12,
    "coral": 45,
    "dark_azure": 78,
    "dark_blue": 307,
    "dark_blue_violet": 32,
    "dark_bluish_gray": 2555,
    "dark_brown": 220,
    "dark_gray": 362,
    "dark_green": 236,
    "dark_nougat": 34,
    "dark_olive_green": 0,  # No quantity provided
    "dark_orange": 148,
    "dark_pink": 63,
    "dark_purple": 62,
    "dark_red": 300,
    "dark_salmon": 3,
    "dark_tan": 362,
    "dark_turquoise": 61,
    "dark_yellow": 9,
    "earth_orange": 45,
    "fabuland_brown": 77,
    "fabuland_lime": 3,
    "fabuland_orange": 6,
    "green": 250,
    "lavender": 42,
    "light_aqua": 42,
    "light_blue": 43,
    "light_bluish_gray": 1888,
    "light_brown": 119,
    "light_gray": 701,
    "light_green": 30,
    "light_lime": 9,
    "light_nougat": 139,
    "light_orange": 41,
    "light_pink": 48,
    "light_purple": 30,
    "light_salmon": 28,
    "light_turquoise": 36,
    "light_violet": 38,
    "light_yellow": 137,
    "lilac": 2,
    "lime": 82,
    "maersk_blue": 32,
    "magenta": 51,
    "medium_azure": 62,
    "medium_blue": 104,
    "medium_brown": 47,
    "medium_dark_pink": 27,
    "medium_green": 44,
    "medium_lavender": 50,
    "medium_lime": 50,
    "medium_nougat": 106,
    "medium_orange": 77,
    "medium_tan": 33,
    "medium_violet": 20,
    "neon_green": 5,
    "neon_orange": 3,
    "neon_yellow": 10,
    "nougat": 119,
    "olive_green": 0,  # No quantity provided
    "orange": 148,
    "pink": 50,
    "purple": 52,
    "red": 2701,
    "reddish_brown": 401,
    "rust": 68,
    "salmon": 27,
    "sand_blue": 124,
    "sand_green": 131,
    "sand_purple": 10,
    "sand_red": 5,
    "sky_blue": 19,
    "tan": 1213,
    "very_light_bluish_gray": 181,
    "very_light_gray": 100,
    "very_light_orange": 12,
    "violet": 42,
    "white": 9102,
    "yellow": 1263,
    "yellowish_green": 44,
    "trans_aqua": 34,
    "trans_black": 2023,
    "trans_bright_green": 3208,
    "trans_brown": 33744,
    "trans_clear": 72268,
    "trans_dark_blue": 7673,
    "trans_dark_pink": 3642,
    "trans_green": 7415,
    "trans_light_blue": 11691,
    "trans_light_bright_green": 51,
    "trans_light_green": 12,
    "trans_light_orange": 51,
    "trans_light_purple": 22,
    "trans_medium_blue": 760,
    "trans_medium_purple": 8,
    "trans_neon_green": 1047,
    "trans_neon_orange": 1326,
    "trans_neon_yellow": 95,
    "trans_orange": 210,
    "trans_pink": 78,
    "trans_purple": 1949,
    "trans_red": 12901,
    "trans_yellow": 8056,
    "chrome_antique_brass": 5,
    "chrome_black": 14,
    "chrome_blue": 3,
    "chrome_gold": 81,
    "chrome_green": 4,
    "chrome_pink": 3,
    "chrome_silver": 75,
    "bionicle_copper": 3,
    "bionicle_gold": 3,
    "bionicle_silver": 3,
    "copper": 63,
    "flat_dark_gold": 48,
    "flat_silver": 99,
    "pearl_black": 5,
    "pearl_dark_gray": 110,
    "pearl_gold": 75,
    "pearl_light_gold": 44,
    "pearl_light_gray": 82,
    "pearl_sand_blue": 9,
    "pearl_sand_purple": 8,  # Updated from 3 to 8
    "pearl_very_light_gray": 27,
    "pearl_white": 6,
    "reddish_copper": 0,  # No quantity provided
    "reddish_gold": 7,
    "satin_trans_bright_green": 7,
    "satin_trans_brown": 10,
    "satin_trans_clear": 26,
    "satin_trans_dark_blue": 25,
    "satin_trans_dark_pink": 6,
    "satin_trans_light_blue": 515,
    "satin_trans_purple": 3,
    "metallic_copper": 0,  # No quantity provided
    "metallic_gold": 68,
    "metallic_green": 10,
    "metallic_silver": 84,
    "glow_in_dark_opaque": 44,
    "glow_in_dark_trans": 7,
    "glow_in_dark_white": 88,
    "milky_white": 38,
    "glitter_trans_clear": 8,
    "glitter_trans_dark_pink": 279,
    "glitter_trans_light_blue": 569,
    "glitter_trans_neon_green": 24,
    "glitter_trans_orange": 5,
    "glitter_trans_purple": 10,

}

piece_3622 = {
    "aqua": 191,
    "black": 224888,
    "blue": 43604,
    "blue_violet": 73,
    "bright_green": 522,
    "bright_light_blue": 4565,
    "bright_light_orange": 7478,
    "bright_light_yellow": 6237,
    "bright_pink": 3839,
    "brown": 4156,
    "clikits_lavender": 17,
    "coral": 81,
    "dark_azure": 4945,
    "dark_blue": 12458,
    "dark_blue_violet": 55,
    "dark_bluish_gray": 210938,
    "dark_brown": 758,
    "dark_gray": 7117,
    "dark_green": 4676,
    "dark_nougat": 73,
    "dark_olive_green": 1,
    "dark_orange": 12086,
    "dark_pink": 2641,
    "dark_purple": 1874,
    "dark_red": 14656,
    "dark_salmon": 3,
    "dark_tan": 2058,
    "dark_turquoise": 8005,
    "dark_yellow": 31,
    "earth_orange": 80,
    "fabuland_brown": 250,
    "fabuland_lime": 4,
    "fabuland_orange": 10,
    "green": 21683,
    "lavender": 132,
    "light_aqua": 820,
    "light_blue": 92,
    "light_bluish_gray": 293488,
    "light_brown": 302,
    "light_gray": 25878,
    "light_green": 53,
    "light_lime": 16,
    "light_nougat": 1641,
    "light_orange": 72,
    "light_pink": 62,
    "light_purple": 76,
    "light_salmon": 43,
    "light_turquoise": 51,
    "light_violet": 72,
    "light_yellow": 296,
    "lilac": 13,
    "lime": 10834,
    "little_robots_blue": 1,
    "maersk_blue": 201,
    "magenta": 176,
    "medium_azure": 2162,
    "medium_blue": 10470,
    "medium_brown": 49,
    "medium_dark_pink": 45,
    "medium_green": 70,
    "medium_lavender": 1946,
    "medium_lime": 50,
    "medium_nougat": 18784,
    "medium_orange": 808,
    "medium_tan": 58,
    "medium_violet": 34,
    "neon_green": 8,
    "neon_orange": 32,
    "neon_yellow": 35,
    "nougat": 269,
    "olive_green": 8161,
    "orange": 13850,
    "pink": 514,
    "purple": 168,
    "red": 80512,
    "reddish_brown": 87978,
    "rust": 102,
    "salmon": 35,
    "sand_blue": 582,
    "sand_green": 17399,
    "sand_purple": 26,
    "sand_red": 34,
    "sky_blue": 54,
    "tan": 143160,
    "very_light_bluish_gray": 429,
    "very_light_gray": 225,
    "very_light_orange": 45,
    "violet": 48,
    "white": 212927,
    "yellow": 55294,
    "yellowish_green": 428,
    "trans_aqua": 53,
    "trans_black": 2023,
    "trans_bright_green": 59,
    "trans_brown": 144,
    "trans_clear": 1672,
    "trans_dark_blue": 125,
    "trans_dark_pink": 147,
    "trans_green": 60,
    "trans_light_blue": 144,
    "trans_light_bright_green": 7,
    "trans_light_green": 11,
    "trans_light_orange": 46,
    "trans_light_purple": 7,
    "trans_medium_blue": 88,
    "trans_medium_purple": 7,
    "trans_neon_green": 63,
    "trans_neon_orange": 55,
    "trans_neon_yellow": 33,
    "trans_orange": 62,
    "trans_pink": 45,
    "trans_purple": 59,
    "trans_red": 79,
    "trans_yellow": 102,
    "chrome_antique_brass": 7,
    "chrome_black": 16,
    "chrome_blue": 13,
    "chrome_gold": 63,
    "chrome_green": 8,
    "chrome_pink": 7,
    "chrome_silver": 318,
    "bionicle_copper": 3,
    "bionicle_gold": 3,
    "bionicle_silver": 3,
    "copper": 69,
    "flat_dark_gold": 54,
    "flat_silver": 259,
    "pearl_black": 10,
    "pearl_dark_gray": 260,
    "pearl_gold": 94,
    "pearl_light_gold": 48,
    "pearl_light_gray": 136,
    "pearl_sand_blue": 10,
    "pearl_very_light_gray": 14,
    "pearl_white": 8,
    "reddish_gold": 7,
    "satin_trans_bright_green": 10,
    "satin_trans_brown": 7,
    "satin_trans_clear": 24,
    "satin_trans_dark_blue": 25,
    "satin_trans_dark_pink": 6,
    "satin_trans_light_blue": 24,
    "satin_trans_purple": 3,
    "metallic_copper": 1,
    "metallic_gold": 66,
    "metallic_green": 23,
    "metallic_silver": 230,
    "glow_in_dark_opaque": 54,
    "glow_in_dark_trans": 17,
    "glow_in_dark_white": 84,
    "milky_white": 39,
    "glitter_trans_clear": 8,
    "glitter_trans_dark_pink": 26,
    "glitter_trans_light_blue": 19,
    "glitter_trans_neon_green": 19,
    "glitter_trans_orange": 3,
    "glitter_trans_purple": 24
}

piece_3755 = {
    "aqua": 1,
    "black": 127,
    "blue": 22,
    "blue_violet": 2,
    "bright_green": 6,
    "bright_light_blue": 7,
    "bright_light_orange": 4,
    "bright_light_yellow": 3,
    "bright_pink": 8,
    "brown": 14,
    "clikits_lavender": 2,
    "coral": 1,
    "dark_azure": 6,
    "dark_blue": 16,
    "dark_blue_violet": 1,
    "dark_bluish_gray": 1088,
    "dark_brown": 14,
    "dark_gray": 213,
    "dark_green": 21,
    "dark_olive_green": 1,
    "dark_orange": 2,
    "dark_pink": 2,
    "dark_purple": 2,
    "dark_red": 32,
    "dark_tan": 24,
    "dark_yellow": 1,
    "earth_orange": 4,
    "fabuland_brown": 7,
    "green": 55,
    "lavender": 4,
    "light_blue": 2,
    "light_bluish_gray": 3298,
    "light_brown": 13,
    "light_gray": 417,
    "light_lime": 1,
    "light_nougat": 19,
    "light_orange": 2,
    "light_yellow": 10,
    "lime": 2,
    "medium_azure": 1,
    "medium_blue": 6,
    "medium_brown": 1,
    "medium_green": 4,
    "medium_lime": 2,
    "medium_nougat": 6,
    "medium_tan": 3,
    "neon_orange": 2,
    "neon_yellow": 2,
    "nougat": 8,
    "olive_green": 2,
    "orange": 9,
    "pink": 1,
    "purple": 1,
    "red": 660,
    "reddish_brown": 42,
    "rust": 5,
    "sand_blue": 4,
    "sand_green": 29,
    "sky_blue": 1,
    "tan": 84,
    "very_light_bluish_gray": 16,
    "very_light_gray": 9,
    "white": 2971,
    "yellow": 333,
    "yellowish_green": 1,
    "trans_brown": 1,
    "trans_clear": 22,
    "trans_dark_blue": 2,
    "trans_light_blue": 11,
    "trans_medium_blue": 11,
    "trans_neon_orange": 3,
    "trans_purple": 1,
    "trans_red": 1,
    "chrome_antique_brass": 2,
    "chrome_black": 1,
    "chrome_gold": 1,
    "chrome_silver": 4,
    "copper": 1,
    "flat_silver": 15,
    "pearl_black": 1,
    "pearl_dark_gray": 6,
    "pearl_gold": 1,
    "pearl_light_gray": 1,
    "pearl_white": 2,
    "metallic_silver": 5,
    "glow_in_dark_white": 3,
}

piece_14716 = {
    "aqua": 19,
    "black": 28176,
    "blue": 201,
    "blue_violet": 5,
    "bright_green": 38,
    "bright_light_blue": 45,
    "bright_light_orange": 998,
    "bright_light_yellow": 896,
    "bright_pink": 328,
    "brown": 365,
    "clikits_lavender": 3,
    "coral": 4,
    "dark_azure": 282,
    "dark_blue": 1598,
    "dark_blue_violet": 11,
    "dark_bluish_gray": 1394,
    "dark_brown": 2891,
    "dark_gray": 206,
    "dark_green": 130,
    "dark_nougat": 11,
    "dark_orange": 381,
    "dark_pink": 5,
    "dark_purple": 324,
    "dark_red": 158,
    "dark_tan": 2136,
    "dark_turquoise": 122,
    "dark_yellow": 2,
    "earth_orange": 12,
    "fabuland_brown": 47,
    "fabuland_lime": 1,
    "fabuland_orange": 7,
    "green": 139,
    "lavender": 9,
    "light_aqua": 9,
    "light_blue": 16,
    "light_bluish_gray": 53449,
    "light_brown": 73,
    "light_gray": 615,
    "light_green": 1,
    "light_lime": 4,
    "light_nougat": 58,
    "light_orange": 7,
    "light_pink": 4,
    "light_purple": 2,
    "light_salmon": 2,
    "light_turquoise": 14,
    "light_yellow": 111,
    "lilac": 1,
    "lime": 406,
    "maersk_blue": 14,
    "magenta": 3,
    "medium_azure": 3199,
    "medium_blue": 374,
    "medium_brown": 14,
    "medium_dark_pink": 3,
    "medium_green": 5,
    "medium_lavender": 22,
    "medium_lime": 6,
    "medium_nougat": 953,
    "medium_orange": 4,
    "medium_tan": 15,
    "medium_violet": 1,
    "neon_green": 1,
    "neon_orange": 3,
    "neon_yellow": 128,
    "nougat": 49,
    "olive_green": 103,
    "orange": 59,
    "pink": 5,
    "purple": 15,
    "red": 11273,
    "reddish_brown": 17391,
    "rust": 40,
    "salmon": 62,
    "sand_blue": 94,
    "sand_green": 943,
    "sand_purple": 2,
    "sand_red": 3,
    "sky_blue": 11,
    "tan": 24869,
    "very_light_bluish_gray": 103,
    "very_light_gray": 98,
    "very_light_orange": 3,
    "violet": 4,
    "white": 35426,
    "yellow": 239,
    "yellowish_green": 7,
    "trans_aqua": 25,
    "trans_black": 1,
    "trans_brown": 41,
    "trans_clear": 72,
    "trans_dark_blue": 5,
    "trans_light_blue": 23,
    "trans_light_orange": 1,
    "trans_light_purple": 1,
    "trans_medium_blue": 22,
    "trans_neon_green": 1,
    "trans_neon_orange": 2,
    "trans_neon_yellow": 1,
    "trans_orange": 2,
    "trans_purple": 1,
    "trans_yellow": 2,
    "chrome_antique_brass": 4,
    "chrome_black": 7,
    "chrome_blue": 1,
    "chrome_gold": 11,
    "chrome_pink": 2,
    "chrome_silver": 36,
    "bionicle_gold": 2,
    "copper": 2,
    "flat_silver": 132,
    "pearl_black": 6,
    "pearl_dark_gray": 38,
    "pearl_gold": 13,
    "pearl_light_gray": 5,
    "pearl_very_light_gray": 2,
    "pearl_white": 2,
    "metallic_copper": 1,
    "metallic_gold": 5,
    "metallic_silver": 14,
    "glow_in_dark_white": 13,
    "milky_white": 1,
    "glitter_trans_purple": 2,
    "mx_violet": 1
}

piece_46212 = {
    "aqua": 3,
    "black": 1606,
    "blue": 138,
    "blue_violet": 1,
    "bright_green": 5,
    "bright_light_blue": 7,
    "bright_light_orange": 4,
    "bright_light_yellow": 5,
    "bright_pink": 11,
    "brown": 43,
    "clikits_lavender": 2,
    "coral": 1,
    "dark_azure": 10,
    "dark_blue": 18,
    "dark_blue_violet": 5,
    "dark_bluish_gray": 849,
    "dark_brown": 28,
    "dark_gray": 79,
    "dark_green": 6,
    "dark_nougat": 4,
    "dark_orange": 11,
    "dark_pink": 7,
    "dark_purple": 5,
    "dark_red": 42,
    "dark_tan": 52,
    "dark_turquoise": 4,
    "dark_yellow": 2,
    "fabuland_brown": 13,
    "fabuland_orange": 1,
    "green": 15,
    "lavender": 1,
    "light_aqua": 4,
    "light_blue": 2,
    "light_bluish_gray": 1034,
    "light_brown": 21,
    "light_gray": 1097,
    "light_lime": 1,
    "light_nougat": 16,
    "light_orange": 2,
    "light_pink": 1,
    "light_turquoise": 1,
    "light_violet": 1,
    "light_yellow": 16,
    "lime": 3,
    "maersk_blue": 4,
    "magenta": 5,
    "medium_azure": 10,
    "medium_blue": 5,
    "medium_brown": 5,
    "medium_green": 3,
    "medium_lavender": 3,
    "medium_lime": 2,
    "medium_nougat": 62,
    "medium_orange": 1,
    "medium_tan": 4,
    "neon_orange": 2,
    "neon_yellow": 2,
    "nougat": 10,
    "olive_green": 5,
    "orange": 12,
    "pink": 3,
    "purple": 3,
    "red": 369,
    "reddish_brown": 68,
    "rust": 9,
    "sand_blue": 5,
    "sand_green": 12,
    "sky_blue": 12,
    "tan": 239,
    "very_light_bluish_gray": 13,
    "very_light_gray": 21,
    "very_light_orange": 3,
    "white": 2505,
    "yellow": 26,
    "trans_aqua": 2,
    "trans_black": 5,
    "trans_bright_green": 1,
    "trans_brown": 2710,
    "trans_clear": 25040,
    "trans_dark_blue": 641,
    "trans_dark_pink": 600,
    "trans_green": 3,
    "trans_light_blue": 8520,
    "trans_light_bright_green": 1,
    "trans_light_orange": 1,
    "trans_light_purple": 2,
    "trans_medium_blue": 34,
    "trans_medium_purple": 1,
    "trans_neon_green": 825,
    "trans_neon_orange": 5,
    "trans_orange": 4770,
    "trans_purple": 281,
    "trans_red": 3,
    "trans_yellow": 2,
    "chrome_black": 5,
    "chrome_blue": 1,
    "chrome_gold": 1,
    "chrome_silver": 2,
    "bionicle_silver": 2,
    "copper": 1,
    "flat_silver": 33,
    "pearl_black": 3,
    "pearl_dark_gray": 5,
    "pearl_gold": 2,
    "pearl_light_gold": 2,
    "pearl_very_light_gray": 1,
    "pearl_white": 1,
    "satin_trans_clear": 1,
    "satin_trans_light_blue": 134,
    "metallic_green": 1,
    "metallic_silver": 3,
    "glitter_trans_clear": 1,
}

piece_49311 = {
    "aqua": 1,
    "black": 1132,
    "blue": 38,
    "blue_violet": 3,
    "bright_green": 5,
    "bright_light_blue": 9,
    "bright_light_orange": 75,
    "bright_light_yellow": 53,
    "brown": 30,
    "clikits_lavender": 3,
    "coral": 2,
    "dark_azure": 1074,
    "dark_blue": 15,
    "dark_blue_violet": 2,
    "dark_bluish_gray": 186,
    "dark_brown": 30,
    "dark_gray": 38,
    "dark_green": 27,
    "dark_orange": 10,
    "dark_pink": 1,
    "dark_purple": 114,
    "dark_red": 29,
    "dark_tan": 31,
    "dark_turquoise": 6,
    "dark_yellow": 3,
    "earth_orange": 4,
    "fabuland_brown": 14,
    "green": 26,
    "lavender": 86,
    "light_blue": 1,
    "light_bluish_gray": 4022,
    "light_brown": 25,
    "light_gray": 139,
    "light_lime": 1,
    "light_nougat": 8,
    "light_pink": 1,
    "light_violet": 6,
    "light_yellow": 10,
    "lime": 3,
    "magenta": 2,
    "medium_azure": 1,
    "medium_blue": 1,
    "medium_brown": 2,
    "medium_dark_pink": 2,
    "medium_green": 3,
    "medium_lavender": 1,
    "medium_lime": 1,
    "medium_nougat": 210,
    "medium_orange": 1,
    "medium_tan": 7,
    "neon_green": 1,
    "neon_orange": 1,
    "neon_yellow": 137,
    "nougat": 6,
    "olive_green": 6,
    "orange": 134,
    "pink": 2,
    "purple": 8,
    "red": 65,
    "reddish_brown": 28,
    "rust": 5,
    "sand_blue": 61,
    "sand_green": 9,
    "sand_red": 2,
    "sky_blue": 6,
    "tan": 1927,
    "very_light_bluish_gray": 13,
    "very_light_gray": 12,
    "very_light_orange": 5,
    "violet": 1,
    "white": 4310,
    "yellow": 21,
    "yellowish_green": 1,
    "trans_black": 1,
    "trans_brown": 23,
    "trans_clear": 45,
    "trans_dark_blue": 1,
    "trans_dark_pink": 1,
    "trans_green": 1,
    "trans_light_blue": 9,
    "trans_medium_blue": 19,
    "trans_neon_yellow": 2,
    "trans_purple": 2,
    "trans_red": 3,
    "trans_yellow": 1,
    "chrome_antique_brass": 2,
    "chrome_black": 1,
    "chrome_gold": 2,
    "chrome_silver": 4,
    "copper": 3,
    "flat_dark_gold": 2,
    "flat_silver": 70,
    "pearl_black": 1,
    "pearl_dark_gray": 5,
    "pearl_gold": 1,
    "pearl_light_gray": 2,
    "metallic_gold": 2,
    "metallic_green": 1,
    "metallic_silver": 4
}

piece_87615 = {
    "black": 2853,
    "blue": 497,
    "bright_light_blue": 1,
    "brown": 5,
    "dark_blue": 1570,
    "dark_bluish_gray": 1628,
    "dark_brown": 2,
    "dark_gray": 6,
    "dark_green": 276,
    "dark_purple": 1,
    "dark_tan": 4,
    "green": 2,
    "light_bluish_gray": 1390,
    "light_brown": 1,
    "light_gray": 3,
    "medium_nougat": 1,
    "medium_orange": 5,
    "orange": 200,
    "red": 632,
    "reddish_brown": 384,
    "sand_blue": 140,
    "tan": 1,
    "very_light_bluish_gray": 1,
    "very_light_gray": 1,
    "white": 1202,
    "yellow": 3,
    "trans_light_blue": 1,
    "trans_light_bright_green": 1,
    "pearl_dark_gray": 1,
}



def calculate_total():
    selected_piece = piece_entry.get()
    selected_color = color_entry.get()

    if selected_piece in ["2038", "2039", "2335", "2336", "2338", "2339", "2340", "2341", "2342", "3001", "3005"]:
        total = globals()[f"piece_{selected_piece}"].get(selected_color, 0)
    else:
        result_label.config(text=f"Piece {selected_piece} not found in inventory", foreground="red")
        return

    result_label.config(text=f"Total quantity of {selected_color} {selected_piece}: {total}", foreground="green")

# Create the main window
window = tk.Tk()
window.title("Inventory Calculator")
window.geometry("400x300")  # Set window size

# Create and place widgets with some styling
style = ttk.Style()
style.configure("TButton", padding=10, font=('Helvetica', 12))
style.configure("TLabel", padding=5, font=('Helvetica', 12))

piece_label = ttk.Label(window, text="Enter the piece number:")
piece_label.pack(pady=10)

piece_entry = ttk.Entry(window, font=('Helvetica', 12))
piece_entry.pack(pady=10)

color_label = ttk.Label(window, text="Enter the color:")
color_label.pack(pady=10)

color_entry = ttk.Entry(window, font=('Helvetica', 12))
color_entry.pack(pady=10)

calculate_button = ttk.Button(window, text="Calculate Total", command=calculate_total)
calculate_button.pack(pady=20)

result_label = ttk.Label(window, text="", font=('Helvetica', 12))
result_label.pack(pady=10)

# Start the Tkinter event loop
window.mainloop()
